* Johan's chess notes
#+TODO: TODO(t) STARTED(s) WAITING(w) | DONE(d) CANCELED(c)
#+STARTUP: overview logdone

* lichess
** game
*** numbers (a+b)
    a (in minutes) is the time you have for thinking and playing your moves in the whole game
    b (in seconds) is the number of time that is added everytime you play a move
    total time for game = a+b*(number of moves)
*** types
    https://en.wikipedia.org/wiki/Fast_chess
    https://lichess.org/faq#time-controls
    bullet      one or two minutes per side
    blitz       less than 10 minutes per side (often 5 minutes)
    rapid       10-60 minutes per side (often 30 minutes)
    classical   may allow two hours per player for the first forty moves, then an additional hour per player

* theory
** [[https://www.reddit.com/r/chess/comments/sbsdht/calculation_advice_seeing_opponents_moves/]]
** [[https://learn.chessbase.com/en/page/the-value-of-the-pieces-in-chess]]

   | piece  | value |
   |--------+-------|
   | Queen  |   9   |
   | Rook   |   5   |
   | Bishop |   3   |
   | Knight |   3   |
   | Pawn   |   1   |

   Two bishops coordinate very well as the bishop pair because they can operate on all the squares on the board In
   an open position (one with few blocked pawns) the bishop pair is stronger thana bishop and a knight. So the
   bishop is worth a tad more than the knight. In a closed position in which the bishops are restricted by blocked
   pawn chains the knight, on the other hand, is more mobile.

** pawn chains
   attack a pawn chain at its base!
   black d5, e6, f7 is a pawn chain, d5 is its base
   white d4, e5 is a pawn chain, d4 is its base; b2, c3, d4, e5 is a strong white pawn chain
* study
** [[https://lichess.org/study/DAmLK0ug][Queen's Gambit]]
   1.  d4 d5
   2.  c4
***    ...  dxc4 (Queens Gambit Accepted)
   3.  Nf3       (to prevent ... e5)
       ...  Nf6
   4.  e3        (so that our Bishop f1 can take back c4)
****   ...  b5   (to greedy, should have played e6)
   5.  a4        (because it is covered by our Queen)
       ...  c6
   6.  axb5 cxb5
   7.  b3        (black behind in development, white has center, destroys black's queenside, may attack the King)
****   ...  e6
   5.  Bc4  c5   (black will try to take on d4 at some point)
   6.  O-O  a6   (black wants to go ... b5 and ... Bb7)
   7.  a4        (attack b5, coverted by our Queen)
       ...  Nc6
   8.  Qe2  cxd4
   9.  Rd1       (pawn d4 pinned to the black Queen)
       ...  Be7
   10. exd4 O-O
   11. Nc3
***    ...  e6   (Queens Gambit declined)
   3.  Nc3  Nf6
   4.  cxd5 exd5
   5.  Bg5       (pin black's Kf6 against black Queen)
       ...  Be7
   6.  e3        (to bring our Bf1 in the game)
       ...  c6   (Carlsbad Pawn Structure)
   7.  Bd3  Nbd7
   8.  Qc2       (put pressure on h7)
       ...  O-O
   9.  O-O       (King side caste is better, but it's not explained)
      *** TO BE CONTINUED ***
***    ...  c6   (Slav and Semi-Slav Defenses)

* puzzles
** [[https://lichess.org/training/cTN9D]]
   Queen can attack Knight Rook
   ... Bxe5
   Nxe5 Qd4
** [[https://lichess.org/training/LlXfB]]
   checkmate the King
   ... Rg3+
   Kf1 Rg1# (Kf1 Qg1#) (Kh1 Qg1#) (Kh2 Qg1
** [[https://lichess.org/training/L9xtk]]
   get the Root at g4
   Qxe6+ Kb8
   Qxg4
** [[https://lichess.org/training/Prait]]
   attack the Queen, Bd6
   Queen has to take Bd6 because otherwise the Bishop would attack the King, any other white move and Bxe5
   ...  Bd6
   Qxd6 Rxd6
** [[https://lichess.org/training/QfoSo]]
   attack Bishop Be7
   ... Qd1+
   Kh2 Qd6+
   g3  Qxe7
** [[https://lichess.org/training/tPtnS]]
   attach Rook Rh1
   ... Rd1+
   Ke2 Rxh1
** [[https://lichess.org/training/8vC5j]]
   Rook Rd8 most valuable
   ... Rd2+
   Kc3 Rxd8
** [[https://lichess.org/training/qJStx]]
   Rook Ra8 most valuable
   ... Qxb7
   e6  Qxa8
** [[https://lichess.org/training/qCYlB]]
   King in check, attach Rook
   ... Qxe6
   Kh8 Qxc8+

** [[https://lichess.org/training/kmTSk]]
   King in check first, attack Rook Rd8
   Rxg7+ Qxg7
   Qxd8+
** [[https://lichess.org/training/FqjWL]]
   King in check, attack Bishop Be4
   Nd6+ Kf8
   Rg8+ Ke7
   Re8#
** [[https://lichess.org/training/z0MZ2]]
   King in check with Queen, Knight sacrified, Bishop gained
   ...  Qh4+
   g3   Nxg3
   Bxg3 Qxg3+
** [[https://lichess.org/training/BBCtc]]
   King in check with Rg4
   Rg4+  Kf8
   Rb8   Qe8
   Rxe8+

** [[https://lichess.org/training/zRb5D]]
   not g3, because Ke3 will travel to Kf2 and takes promoted g1
   ... gxh5
   f5  Kd5
** [[https://lichess.org/training/pP4wW]]
   Rook blocks attack on King, discovered attack on King by Qb6
   ... Re5
   Kf1 Rxf5

** STARTED [[https://lichess.org/training/wDGzM]]

* games
** [[https://lichess.org/ET9gRysx]]
    1. e4 { [%eval 0.25] } 1... e6 { [%eval 0.29] }
    2. d4 { [%eval 0.24] } 2... d5 { [%eval 0.25] } { C00 French Defense }
    3. Bb5+ { [%eval -0.16] } 3... Nc6 { [%eval 0.33] }
    4. c3? { (0.33 → -0.85) Mistake. Nc3 was best. } { [%eval -0.85] } (4. Nc3 a6 5. Bxc6+ bxc6 6. Nf3 Nf6 7. Bg5
       Be7 8. Bxf6 Bxf6) 4... dxe4 { [%eval -0.64] }
    5. Be3 { [%eval -1.01] } 5... Qxd4?? { (-1.01 → 10.43) Blunder. f5 was best. } { [%eval 10.43] }
       (5... f5 6. Nh3)
    6. Bxd4 { [%eval 10.11] } 6... Nf6 { [%eval 10.48] }
    7. Nd2 { [%eval 10.38] } 7... Bc5 { [%eval 15.38] }
    8. Nh3 { [%eval 9.97] } 8... Bxd4 { [%eval 9.94] }
    9. Bxc6+ { [%eval 10.07] } 9... bxc6 { [%eval 10.04] }
   10. Nc4 { [%eval 6.69] } 10... Bxf2+ { [%eval 9.55] }
   11. Nxf2 { [%eval 9.67] } 11... O-O { [%eval 9.44] }
   12. O-O { [%eval 8.76] } 12... Rd8? { (8.76 → Mate in 2) Checkmate is now unavoidable. Ba6 was best. } { [%eval
       #2] } (12... Ba6 13. Qe2 e3 14. Nd1 Nd5 15. b3 f5 16. Ndxe3 Nxe3 17. Qxe3 Bxc4 18. bxc4 Rfe8 19. Qc5)
   13. Qxd8+ { [%eval #1] } 13... Ne8 { [%eval #1] }
   14. Qxe8# { White wins by checkmate. } 1-0
** blitz
*** https://lichess.org/izIEuMyn, first victory against a real person
    1. e4 e5 2. Nf3 Nf6 3. Nxe5 d6 { C42 Russian Game } 4. Bb5+?? { (0.37 → -3.66) Blunder. Nf3 was best. }
    (4. Nf3 Nxe4 5. d4 d5 6. Bd3 Bd6 7. O-O O-O 8. c4 c6) 4... c6 5. Bxc6+? { (-3.41 → -5.63) Mistake. Nxf7 was
    best. } (5. Nxf7 Kxf7 6. Bd3 Nbd7 7. f3 d5 8. Be2 dxe4 9. fxe4 Nxe4) 5... bxc6 6. Nxc6?! { (-5.90 → -8.69)
    Inaccuracy. Nf3 was best. } (6. Nf3) 6... Nxc6 7. e5 dxe5 8. d4 Bb4+ 9. Bd2 Ba5 10. f4 exf4 11. Kf2
    Bg4 12. g3?! { (-10.07 → Mate in 7) Checkmate is now unavoidable. Re1+ was best. } (12. Re1+ Kf8 13. Bxa5
    Qxa5 14. Qd2 Qxd2+ 15. Nxd2 Nxd4 16. Rac1 Bf5 17. Kg1 Nxc2 18. Re5 Nd4) 12... Bxd1?! { (Mate in 7 → -20.42)
    Lost forced checkmate sequence. Qxd4+ was best. } (12... Qxd4+ 13. Kf1 Qe4 14. Qe1 Bh3+ 15. Kf2 Ng4+ 16. Kg1
    Qxe1+ 17. Bxe1 Bb6+ 18. Bf2 Bxf2#) 13. gxf4?! { (-20.42 → Mate in 6) Checkmate is now unavoidable. Re1+ was
    best. } (13. Re1+ Kf8 14. Bc3 Bxc2 15. Bxa5 Qxd4+ 16. Kg2 Qxb2 17. Nd2 Nxa5 18. Kh1 Qd4 19. Nb3 Nxb3)
    13... Bxc2?! { (Mate in 6 → -20.66) Lost forced checkmate sequence. Qxd4+ was best. } (13... Qxd4+ 14. Be3
    Ng4+ 15. Kg2 Qe4+ 16. Kg1 Qxe3+ 17. Kg2 Qf3+ 18. Kg1 Bb6#) 14. Nc3 g5 15. Be3 gxf4 16. Bxf4?! { (-23.80 → Mate
    in 7) Checkmate is now unavoidable. Rhe1 was best. } (16. Rhe1 fxe3+) 16... Qxd4+ 17. Kf3 O-O-O?! { (Mate in 7
    → -27.54) Lost forced checkmate sequence. Bxc3 was best. } (17... Bxc3 18. Rhe1+ Be4+ 19. Rxe4+ Qxe4+ 20. Kg3
    Rg8+ 21. Bg5 Rxg5+ 22. Kf2 Rg2+ 23. Kf1 Qe2#) 18. Rad1 Qd3+ 19. Kf2?! { (-18.80 → Mate in 7) Checkmate is now
    unavoidable. Rxd3 was best. } (19. Rxd3 Rxd3+ 20. Be3 Rxc3 21. bxc3 Be4+ 22. Ke2 Bxh1 23. Kd3 Be4+ 24. Kc4
    Bd5+ 25. Kd3 Bxa2) 19... Bxd1 20. Nd5 Qxd5 21. Kg3 Qxh1 22. Kh4 Rd4 23. h3 Rxf4+ 24. Kg5 Rg8+ 25. Kh6 Rh4# {
    Black wins by checkmate. } 0-1
