* Johan's chess notes
#+TODO: TODO(t) STARTED(s) WAITING(w) | DONE(d) CANCELED(c)
#+STARTUP: overview logdone

* puzzles
** https://lichess.org/training/3La0T
Block black from reaching rank 1.  As black can take ...xa3 we need to move a3 out of the way first.  1. a4
g4 2. h4 success
** https://lichess.org/training/K0NBg
Give up our queen and rook.  Black will take the queen with the knight at d7; c8 and d7 will be covered by our
bisscheop at h3.  We take the black rook at f8 with our pawn at g8.  gxf8=Q# success
** https://lichess.org/training/cgzRP
Give up our rook when we attack the black king.  We take the black knight with our queen.  Next we attack the
black king with our bisshop.  Bh7 and the black king will take it.  We capture the black queen.  Qxf8 success
** https://lichess.org/training/7WtZ8
Attack the white queen with black bishop, Ba6.  To save its queen white can only Qxa6, and we take it by Kxa6.
** https://lichess.org/training/VYiZn
Black king on f6 is easy to checkmate with queen, and queen will be protected by pawn on h4.  1. Bf6 Kxf6 2. Qg5#
** https://lichess.org/training/Qqg2o
Attack black king with our queen.  The black king will take our queen.  1. Qh6+ Kxh6 2. Rh3+ Kg5 3. f4#
** https://lichess.org/training/JaCJ7
Checkmate black king with h7# after it is on g8.  g8 covers f7 and h7.  g7 covers f8 and h8.  1. g6+ Kh8 2. Bg7+
Kg8 3. h7#
** https://lichess.org/training/N9KZz
1. ...Qd6 attacks h2 with c7 as its backup.  Black queen on h2 would put white King in check.  1. ...Qd6 2. g3
   Bxa5
** https://lichess.org/training/Brdyf
Attack king with rook so that the black knight will block h8.  Attack the king again but with the
bisshop.  1. Rh8+ Nxh8 2. Bh7#
** https://lichess.org/training/x3oDl
Attack black king with white bisshop, but first make sure to get rid of Nd4.  In the end we gain the black knight,
the black queen, and the black bisshop.  We lose our queen and our bisshop.  1. Nxd4 Bxe2 2. Bb5+ Qd7 3. Bxd7+
Kxd7 4. Nxe2
** https://lichess.org/training/k0a0N
Checkmate black king on g6 with white queen on f5, protected by white king on f4.  1. Qc8+ Kh7 2. g6+
fxg6 3. fxg6+ Kxg6 4. Qf5#
** https://lichess.org/training/pyXxx
The goal is to capture the black rook at f4.  Our white rook will be protected by our king at g3.  1. Rg7+
Kf5 2. Rf7+ Ke5 3. Rxf4
** https://lichess.org/training/2yZEg
Checkmate black king on h1 with rook at h2.  Black queen attacks first.  1. ...Qxg2+ 2. Nxg2 Nf3+ 3. Kh1
Rxh3+ 4. Bh2 Rxh2#
** https://lichess.org/training/qQce1
Our knight at e7 would block g8 and g6 and would force the black king to h7. Rook at h1 will then checkmate the
black king.  1. Qxg5 hxg5 2. Ne7+ Kh7 3. Rh1#
** https://lichess.org/training/Y9B6H
Try to reach rank 1.  1. ... g5 2. Kd4 h4 3. gxh4 gxh4
** https://lichess.org/training/FPfGr
Attack king with knight.  Once the king is on h6 we see that g7 and g5 become unavailable.  Queen at h1 is
checkmate. 1. ... Nxe6+ 2. Kh6 Qh1#
** https://lichess.org/training/tDUpI
Capture the queen!  First we attack the king with our queen.  Then we attack the king with our knight at c6.  Our
knight at c6 can capture the queen at e7.  1. Qa6+ Kb8 2. Nxc6+ Ka8 3. Nxe7
** https://lichess.org/training/5YK8f
We can capture the black bisshop by attacking the black queen.  1. Ne2 Qd6 2. Nxf4
** https://lichess.org/training/Huh0z
We can checkmate the king by bringing him to file h.  With the king on h6 we block g7, h7, and g5.  A rook on h8
also blocks h5.  1. Qxf8+ Kxf8 2. Rxf7+ Kg8 3. Rf8+ Kh7 4. R1f7+ Kh6 5. Rh8#
** https://lichess.org/training/ubqw1
We can checkmate the king with our rook.  Our attacking rook is covered by the other Rf8.  1. ... Qxf1+ 2. Kxf1
Rxf2+ 3. Kg1 Rf1#
** https://lichess.org/training/veIHw
Attack the queen.  The goal is to attack the knight at c4 and get rid of the bisshop at e6.  1. Nc3 Qc6 2. Nxc4
Bxc4  3. Qxc4
** https://lichess.org/training/SpWA1
Qc8+ isn't an option.  The black rook at d3 and knight at c6 can block us.  1. Qe6+ Kh8 2. Qe8+ Qf8 Both Qxf8#
and Rxf8# give us checkmate.
** https://lichess.org/training/LSZmD
We will lose our queen when attacking the black queen, but gain it back with our white pawn on f6.  1. Qxg5
Nxg5. 2. fxe7 Nxe6. 3. e8=Q
** https://lichess.org/training/akefu
Pawn to d2 forces the rook to move.  We can then attack the king with our bisshop.  1. ... d2 2. Rd6 Bc7 3. Kf2
Bxd6
Nxg5 2. fxe7 Nxe6 3. e8=Q
** https://lichess.org/training/XQ5eg
Attack the king with our rook, and then with the pawn at b2.  The black rook cannot attack us because the king has
to take our pawn at b4.  1. Rd3+ Kc5 2. b4+ Kxb4 3. Rxd6
** https://lichess.org/training/jCHwY
Attack the king with bisshop at d5 by moving our rook.  1. Re8+ Re6 2. Bxe6+ Kh8 3. Rxf8#
** https://lichess.org/training/xHMGF
We can reach rank 8 with our pawn.  1. d6+ Kd7 2. dxe7
** https://lichess.org/training/2qnYk
Attack with bisshop, and then attack the white pawn in the a file.  We do not attack the pawn in the c file as the
king can escape by means of Kd3.  1. ... Ba3+ 2. Kb1 bxa2+ 3. Ka1 Qb2#
** https://lichess.org/training/HPEmW
Attacking the rook at h8 by means of Nf7 forces the queen on f7.  1. Nxf7 Qxf7 2. Bg6 O-O-O 3. Bxf7
** https://lichess.org/training/DPPRs
A bisshop on f7 attacks the king while protected by our knight on e5.  f7 isn't under attack by any white
piece.  1. Nf6+ gxf6 2. Bxf7#
** https://lichess.org/training/Z3oln
Threaten the king and block the black queen, next attack the queen.  Our queen at b3 covers a2, b2, b1, and c3.
d4 is guarded by e3.  1. Qb3+ Kh7 2. Rc1 Qxc1 3. Rxc1
* lucas chess
** [TimeStart "2022.08.02 08:35:34"][White "Ufim 8.02 (700)"][Black "gargle"]
[Event "Play against an engine"]
[Site "Lucas Chess R2.0"]
[Date "2022.08.02"]
[White "Ufim 8.02 (700)"]
[Black "gargle"]
[Result "0-1"]
[ECO "A20"]
[TimeStart "2022.08.02 08:35:34"]
[Termination "Mate"]
[Opening "English Opening: King Indian Defense"]
[PlyCount "52"]
[TimeEnd "2022.08.02 08:41:47"]

1.c4 (1.d4 {+0.43 pws Stockfish 14.1 64-bmi2}) (1.Nf3 {+0.35 pws Stockfish 14.1 64-bmi2} c5 2.e4 d6 3.Bb5+ Nd7
4.O-O a6 5.Bxd7+ Bxd7 6.d4 cxd4 7.Qxd4 e5 8.Qd3 Nf6) (1.c4 {+0.33 pws Stockfish 14.1 64-bmi2} c5 2.g3 g6 3.Bg2 Bg7
4.e3 e5 5.Ne2 Nc6 6.Nbc3 Nge7 7.b3 d6 8.d3 O-O) (1.e4 {+0.31 pws Stockfish 14.1 64-bmi2} c5 2.Nf3 d6 3.Bb5+ Nd7
4.O-O a6 5.Bxd7+ Bxd7 6.d4 cxd4 7.Qxd4 Rc8 8.c4 Nf6 9.Nc3 e5 10.Qd3 Be7) (1.g3 {+0.30 pws Stockfish 14.1 64-bmi2}
c5 2.c4 Nc6 3.Nc3 g6 4.Bg2 Bg7 5.e3 d6 6.Nge2 h5 7.h3 Nf6 8.d4 h4 9.d5) (1.e3 {+0.16 pws Stockfish 14.1 64-bmi2}
e5 2.d4 exd4 3.exd4 Nf6 4.Nf3 d5 5.Bd3 Bd6 6.O-O O-O 7.Re1 c6 8.Bg5 Bg4 9.h3 Bh5) (1.c3 {+0.12 pws Stockfish 14.1
64-bmi2} Nf6 2.d4 d5 3.Nf3 Bf5 4.Qb3 Qc8 5.c4 dxc4 6.Qxc4 a6 7.g3 b5 8.Qb3 c5) (1.Nc3 {+0.00 pws Stockfish 14.1
64-bmi2} d5 2.d4 Nf6 3.Bf4 a6 4.e3 e6 5.Bd3 c5 6.dxc5 Bxc5 7.Nf3 Nc6 8.e4 O-O 9.O-O h6 10.e5 Nd7) (1.a3 {-0.14 pws
Stockfish 14.1 64-bmi2} c5 2.e4 g6 3.Nf3 Bg7 4.d4 cxd4 5.Nxd4 d6 6.Nb3 Nc6 7.Be2 Qc7 8.O-O Nf6) (1.h3 {-0.16 pws
Stockfish 14.1 64-bmi2} e5 2.c4 Nf6 3.d3 Bb4+ 4.Bd2 Bxd2+ 5.Qxd2 c5 6.e3 Nc6 7.Nc3 d5 8.cxd5 Nxd5 9.Nf3) e5
(1... c5 {+0.27 pws Stockfish 14.1 64-bmi2} 2.g3 Nc6 3.Nc3 g6 4.Nf3 Bg7 5.Bg2 d6 6.O-O e6 7.e3 Nge7 8.d4 O-O)
(1... e5 {+0.30 pws Stockfish 14.1 64-bmi2} 2.g3 Nf6 3.Bg2 c6 4.Nf3 e4 5.Nd4 d5 6.d3 dxc4 7.dxe4 Bc5 8.e3 Nbd7
9.Nc3 O-O) (1... e6 {+0.45 pws Stockfish 14.1 64-bmi2} 2.d4 d5 3.Nc3 Nf6 4.Bg5 Be7 5.Nf3 O-O 6.e3 Nbd7 7.cxd5 Nxd5
8.Bxe7 Qxe7) (1... g6 {+0.46 pws Stockfish 14.1 64-bmi2} 2.d4 Nf6 3.Nc3 d5 4.Nf3 Bg7 5.cxd5 Nxd5 6.e4 Nxc3 7.bxc3
c5 8.Be2 O-O 9.Rb1 Bg4 10.Rxb7 Bxf3 11.Bxf3 cxd4) (1... Nf6 {+0.47 pws Stockfish 14.1 64-bmi2} 2.d4 e6 3.Nf3 d5
4.g3 Bb4+ 5.Bd2 a5 6.Bg2 O-O 7.O-O dxc4 8.Qc2 Bxd2 9.Nbxd2) (1... d6 {+0.49 pws Stockfish 14.1 64-bmi2} 2.d4 e5
3.Nf3 e4 4.Ng5 f5 5.Nh3 Nd7 6.Nc3 Nb6 7.Nf4 Nf6 8.e3 Be7 9.b3 d5) (1... c6 {+0.51 pws Stockfish 14.1 64-bmi2}
2.Nf3 d5 3.d4 e6 4.e3 Bd6 5.Bd3 f5 6.O-O Nf6 7.Qc2 Ne4 8.b3 Nd7) (1... a6 {+0.66 pws Stockfish 14.1 64-bmi2} 2.d4
e6 3.e4 d5 4.exd5 exd5 5.Nf3 Nf6 6.Nc3 Bb4 7.Bd3 dxc4 8.Bxc4 b5 9.Bd3 O-O 10.O-O Re8 11.a3) (1... h6 {+0.67 pws
Stockfish 14.1 64-bmi2} 2.Nf3 e6 3.e4 d5 4.cxd5 exd5 5.exd5 Nf6 6.Bc4 Be7 7.O-O Nbd7 8.Nc3 Nb6 9.Re1 Nxc4 10.Qa4+
Bd7 11.Qxc4) (1... Nc6 {+0.75 pws Stockfish 14.1 64-bmi2} 2.d4) 2.d3 ?! (2.g3 {+0.54 pws Stockfish 14.1 64-bmi2}
d6 3.Bg2 Nc6 4.d3 g6 5.Nc3 Bg7 6.e3 a5 7.b3 h5 8.h4 Nf6 9.Nge2 O-O 10.O-O) (2.Nc3 {+0.22 pws Stockfish 14.1
64-bmi2} Bb4 3.Nd5 Be7 4.Nf3 d6 5.g3 c6 6.Nxe7 Nxe7 7.Bg2 c5 8.e3 f5 9.O-O O-O 10.d4 e4 11.Nd2) (2.a3 {+0.06 pws
Stockfish 14.1 64-bmi2} c6 3.Nf3 e4 4.Nd4 d5 5.cxd5 Nf6 6.d3 Bc5 7.dxe4 Nxe4 8.e3 cxd5 9.b4 Bb6 10.Bb2 Nc6 11.Nxc6
bxc6 12.Nd2) (2.d3 {+0.06 pws Stockfish 14.1 64-bmi2} Nf6 3.Nf3 Nc6 4.a3 d5 5.cxd5 Nxd5 6.e3 Bd6 7.Be2 O-O 8.O-O
a5 9.b3 Qf6 10.Bb2 Qg6 11.Nbd2) (2.e3 {+0.00 pws Stockfish 14.1 64-bmi2} Nf6 3.Nc3 d5 4.cxd5 Nxd5 5.Nf3 Nc6 6.Bb5
Nxc3 7.bxc3 Bd6 8.e4 O-O 9.O-O a6 10.Bxc6 bxc6 11.h3 c5 12.Re1 f6 13.d4) (2.Nf3 {-0.07 pws Stockfish 14.1 64-bmi2}
e4 3.Nd4 Nc6 4.e3 Nf6 5.Nc3 Bb4 6.Qc2 Nxd4 7.exd4 c6 8.a3 Ba5 9.d3 Qe7 10.Be3 d5 11.b4 Bc7 12.cxd5) (2.b3 {-0.13
pws Stockfish 14.1 64-bmi2} Nf6 3.Bb2 Nc6 4.e3 d5 5.cxd5 Nxd5 6.a3 Bd6 7.d3 Qe7 8.Nf3 Be6 9.b4 O-O 10.Be2 f5
11.b5) (2.Qc2 {-0.18 pws Stockfish 14.1 64-bmi2} Nf6 3.Nc3 c5 4.Nf3 Nc6 5.e4 d6 6.d3 Be7 7.g3 O-O 8.Bg2 Ne8 9.O-O
Nc7) (2.h3 {-0.19 pws Stockfish 14.1 64-bmi2} Nf6 3.d3 d5 4.cxd5 Nxd5 5.Nf3 f6 6.e4 Nb6 7.d4 exd4 8.Qxd4 Qxd4
9.Nxd4 Bd7 10.Nc3 Nc6) (2.Qa4 {-0.22 pws Stockfish 14.1 64-bmi2} g6 3.g3 Bg7 4.Bg2 Ne7 5.Nc3 O-O 6.d3 c6 7.e4 Na6
8.Nge2 Nc5 9.Qc2 f5 10.O-O) Bc5 (2... Nf6 {+0.00 pws Stockfish 14.1 64-bmi2} 3.Nf3 Nc6 4.a3 d5 5.cxd5 Nxd5 6.e4
Nb6 7.Be3 Be7 8.Be2 O-O 9.O-O a5 10.Qc2 Be6 11.Nc3 a4) (2...  Bb4+ {+0.12 pws Stockfish 14.1 64-bmi2} 3.Bd2 c5
4.g3 Nf6 5.Bg2 Nc6 6.Nc3 d6 7.e4 Nd4 8.h3 a6 9.a3 Ba5 10.Nge2 O-O 11.O-O) (2... Nc6 {+0.13 pws Stockfish 14.1
64-bmi2} 3.Nf3 Nf6 4.Nc3 d5 5.cxd5 Nxd5 6.e4 Nf6 7.h3 Bc5 8.Be3 Bb6 9.Be2 O-O 10.Rc1 h6 11.O-O Re8) (2... Ne7
{+0.13 pws Stockfish 14.1 64-bmi2} 3.Nf3 Nbc6 4.Nc3 d5 5.cxd5 Nxd5 6.e4 Nf6 7.h3 Bc5 8.Be3 Bb6 9.Be2 O-O 10.Rc1 h6
11.O-O Re8) (2... g6 {+0.21 pws Stockfish 14.1 64-bmi2} 3.Nc3 Bg7 4.g3 Ne7 5.Bg2 O-O 6.e4 a5 7.Nge2 d6 8.O-O Na6
9.Rb1 Nc6 10.a3 Nd4 11.Nxd4) (2... a5 {+0.26 pws Stockfish 14.1 64-bmi2} 3.g3 Nf6 4.Nf3 Bb4+ 5.Nc3 d5 6.cxd5 Nxd5
7.Bd2 Nc6 8.Bg2 Nf6 9.a3 Be7 10.Nb5 O-O) (2... Bc5 {+0.28 pws Stockfish 14.1 64-bmi2} 3.e3 Nf6 4.Nf3 d6 5.Be2 O-O
6.O-O Bb6 7.b4 c6 8.a4 Bc7 9.Nc3 d5 10.a5) (2... d6 {+0.29 pws Stockfish 14.1 64-bmi2} 3.Nc3 g6 4.g3 Bg7 5.Bg2 Ne7
6.Rb1 a5 7.a3 O-O 8.Nf3 c6 9.Qc2 d5 10.O-O) (2... Be7 {+0.33 pws Stockfish 14.1 64-bmi2} 3.Nf3 d6 4.g3 f5 5.Bg2 a5
6.O-O Nf6 7.Nc3 O-O 8.a3 c6 9.Rb1 Na6) (2... f5 {+0.37 pws Stockfish 14.1 64-bmi2} 3.Nc3 Nc6 4.Nf3 Nf6 5.g3 Bb4
6.Bd2 a5 7.a3 Bc5 8.Bg2 O-O 9.O-O d6 10.e3 h6) 3.e3 (3.Nf3 {+0.36 pws Stockfish 14.1 64-bmi2} d6 4.g3 Nf6 5.Bg2
O-O 6.Nc3 Re8 7.d4 exd4 8.Nxd4 Bb4 9.Bd2 Nbd7 10.O-O c6 11.a3 Ba5) (3.e3 {+0.32 pws Stockfish 14.1 64-bmi2} Nf6
4.Nf3 d6 5.Be2 O-O 6.O-O Bb6 7.b4 Re8 8.Nc3 c6 9.a4 d5 10.a5 Bc7 11.Bb2 Bd6) (3.g3 {+0.31 pws Stockfish 14.1
64-bmi2} Nf6 4.Bg2 O-O 5.Nf3 Re8 6.O-O d6 7.Nc3 c6 8.Na4 Bb4 9.a3 Ba5 10.Qc2 h6 11.b4) (3.Nc3 {+0.25 pws Stockfish
14.1 64-bmi2} Nf6 4.g3 O-O 5.Bg2 Re8 6.Nf3 Bb6 7.O-O c6 8.Bg5 h6 9.Bxf6 Qxf6 10.e3 d6 11.b4) (3.a3 {+0.22 pws
Stockfish 14.1 64-bmi2} Nf6 4.Nf3 d6 5.b4 Bb6 6.Bb2 O-O 7.e3 Re8 8.Be2 c6 9.O-O a5 10.Qc2 Nbd7 11.Rc1) (3.Qc2
{+0.12 pws Stockfish 14.1 64-bmi2} Nf6 4.Nf3 d6 5.e3 Bf5 6.Nh4 Be6 7.Be2 a5 8.O-O Nc6 9.Nf3 h6 10.a3 O-O) (3.h3
{+0.04 pws Stockfish 14.1 64-bmi2} Nf6 4.Nf3 Nc6 5.a3 d5 6.cxd5 Nxd5 7.e3 a5 8.Be2 Qe7 9.O-O O-O 10.Bd2 f5 11.Nc3
Be6 12.Qc2 Kh8) (3.Bd2 {+0.04 pws Stockfish 14.1 64-bmi2} Nf6 4.Nf3 d6 5.Nc3 O-O 6.e3 Bb6 7.Na4 c5 8.Be2 Bc7 9.a3
Re8 10.Qc2 Nc6) (3.Qa4 {+0.03 pws Stockfish 14.1 64-bmi2} Nf6 4.Nf3 Nc6 5.e3 O-O 6.a3 d5 7.cxd5 Nxd5 8.Qc2 Qe7
9.Be2 a5 10.O-O Kh8 11.Nc3 Nxc3) (3.Nd2 {-0.07 pws Stockfish 14.1 64-bmi2} Nf6 4.Ngf3 Nc6 5.a3 a5 6.e3 O-O 7.Qa4
Ra6 8.Be2 Re8 9.O-O h6 10.Rd1 d5 11.cxd5 Nxd5) Nf6 (3... d5 {+0.21 pws Stockfish 14.1 64-bmi2} 4.cxd5 Nf6 5.Nf3
Qxd5 6.a3 O-O 7.Nc3 Qe6 8.Be2 Rd8 9.b4 Bf8 10.Qc2 c5 11.bxc5 Bxc5 12.Bb2 Nc6) (3... Nf6 {+0.22 pws Stockfish 14.1
64-bmi2} 4.Nf3 d6 5.a3 Bb6 6.Be2 O-O 7.b4 Re8 8.Bb2 c6 9.O-O Bc7 10.Nbd2 d5 11.Qc2 h6 12.Rfc1) (3... d6 {+0.39 pws
Stockfish 14.1 64-bmi2} 4.Be2 Nf6 5.Nf3 O-O 6.O-O Bb6 7.b4 Re8 8.Nc3 c6 9.a4 d5 10.a5 Bc7 11.Qb3 dxc4 12.dxc4)
(3... Bb6 {+0.39 pws Stockfish 14.1 64-bmi2} 4.Nf3 d6 5.Be2 Nf6 6.b4 O-O 7.O-O Re8 8.Nc3 c6 9.a4 d5 10.a5 Bc7
11.Qb3 dxc4 12.dxc4 Qe7) (3... Qe7 {+0.41 pws Stockfish 14.1 64-bmi2} 4.Be2 Nf6 5.Nf3 O-O 6.O-O Re8 7.Nc3 d6 8.a3
a5 9.d4 Bb6 10.c5 exd4 11.cxb6 dxc3 12.bxc7 Qxc7 13.bxc3) (3... Nc6 {+0.43 pws Stockfish 14.1 64-bmi2} 4.Nf3 d6
5.Be2 Nf6 6.O-O O-O 7.Nc3 Re8 8.a3 a5 9.b3 Bb6 10.Nd2 Ne7 11.Nde4 Nxe4 12.dxe4 Ng6 13.Bb2) (3... Bb4+ {+0.47 pws
Stockfish 14.1 64-bmi2} 4.Nd2 Be7 5.Ngf3 Nc6 6.a3 a5 7.Qa4 Nf6 8.b4 d6 9.b5 Nb8 10.Be2 O-O 11.O-O Bf5 12.Bb2 Re8
13.Rfd1) (3... c6 {+0.53 pws Stockfish 14.1 64-bmi2} 4.Nf3 d6 5.d4 Bb4+ 6.Nbd2 Bxd2+ 7.Bxd2 e4 8.Ng1 Nf6 9.Ne2 O-O
10.Ng3 d5 11.a4 Re8 12.Qb3 Nbd7 13.Be2 Nf8 14.a5) (3... Be7 {+0.61 pws Stockfish 14.1 64-bmi2} 4.Nf3 Nc6 5.a3 Nf6
6.b4 d5 7.cxd5 Nxd5 8.b5) (3... a5 {+0.77 pws Stockfish 14.1 64-bmi2} 4.d4 Bb4+ 5.Nc3 exd4 6.exd4 Nf6 7.Bd3 d5
8.c5 Bxc3+ 9.bxc3) 4.Nc3 (4.Nf3 {+0.42 pws Stockfish 14.1 64-bmi2} d6 5.Be2 O-O 6.O-O Nc6 7.Nc3 Re8 8.a3 a5 9.b3
h6 10.Nd2 Ne7 11.Nde4 Nxe4 12.dxe4 Ng6 13.Kh1 Nf8) (4.Nc3 {+0.12 pws Stockfish 14.1 64-bmi2} O-O 5.d4 exd4 6.exd4
Bb6 7.Be2 c6 8.d5 cxd5 9.cxd5 d6 10.Nf3 Nbd7 11.O-O Ne5 12.Nxe5 dxe5 13.Qb3 Re8) (4.Be2 {+0.06 pws Stockfish 14.1
64-bmi2} O-O 5.a3 d5 6.cxd5 Nxd5 7.Qc2 Bd6 8.Nf3 c5 9.O-O Nc6 10.Nbd2 Bf5 11.Ne4 Rc8 12.Rd1) (4.d4 {+0.05 pws
Stockfish 14.1 64-bmi2} exd4 5.exd4 Bb4+ 6.Nc3 Nc6 7.Nf3 d5 8.Bd3 dxc4 9.Bxc4 Qe7+ 10.Be3 Be6 11.Bxe6 Qxe6 12.O-O)
(4.a3 {+0.01 pws Stockfish 14.1 64-bmi2} d5 5.cxd5 Nxd5 6.Nf3 Bd6 7.Be2 c5 8.Nbd2 O-O 9.Qc2 b6 10.b3 Bb7 11.Bb2
Nc6 12.O-O Rc8) (4.h3 {-0.04 pws Stockfish 14.1 64-bmi2} O-O) (4.Bd2 {-0.06 pws Stockfish 14.1 64-bmi2} d6 5.Nc3
Bb6 6.Na4 c5 7.Nf3 Bc7 8.Be2 O-O 9.O-O Nc6 10.a3 d5 11.cxd5 Qxd5) (4.Qc2 {-0.07 pws Stockfish 14.1 64-bmi2} O-O
5.Nf3 Re8 6.b3 Bf8 7.Bb2 d6 8.Be2 h6 9.Nbd2 Bf5 10.h3 Nbd7 11.g4 Bh7 12.Rg1) (4.Nd2 {-0.11 pws Stockfish 14.1
64-bmi2} O-O 5.Ngf3 Re8 6.b3 d5 7.cxd5 Nxd5 8.Qc2 Bf8 9.Bb2 f6 10.d4 exd4 11.Nxd4 c5 12.N4f3 Nb4 13.Qb1) (4.b3
{-0.14 pws Stockfish 14.1 64-bmi2} O-O 5.Nf3 Bb4+ 6.Bd2 Bd6 7.Be2 Re8 8.Qc2 c6 9.O-O Bc7 10.Rc1 Na6 11.b4 d5
12.cxd5 cxd5) d5 (4... O-O {+0.05 pws Stockfish 14.1 64-bmi2} 5.d4 exd4 6.exd4 Bb6 7.Nf3 c6 8.Be2 d5 9.O-O dxc4
10.Bxc4 Bg4 11.Bf4 Bh5 12.Re1 Nbd7) (4... Bb6 {+0.09 pws Stockfish 14.1 64-bmi2} 5.Nf3 Qe7 6.Be2 c6 7.O-O d5
8.cxd5 cxd5 9.Qb3 d4 10.exd4 exd4 11.Ne4 Nxe4 12.dxe4 O-O 13.Bc4) (4...  Nc6 {+0.11 pws Stockfish 14.1 64-bmi2}
5.Nf3 d5 6.cxd5 Nxd5 7.Be2 O-O 8.O-O Re8 9.Bd2 h6 10.a3 Bf8 11.Qc2 Be6 12.b4) (4... d5 {+0.13 pws Stockfish 14.1
64-bmi2} 5.cxd5 Nxd5 6.Nf3 Nc6 7.Be2 O-O 8.O-O h6 9.a3 Nxc3 10.bxc3 Bf5 11.d4 Bd6) (4...  Qe7 {+0.15 pws Stockfish
14.1 64-bmi2}) (4... Bb4 {+0.31 pws Stockfish 14.1 64-bmi2} 5.Bd2 Ba5 6.Nf3 d6 7.d4 Nbd7 8.Qc2 O-O 9.O-O-O Re8
10.h3 e4 11.Ng5 Bxc3 12.Bxc3) (4... d6 {+0.34 pws Stockfish 14.1 64-bmi2} 5.d4 Bb6 6.dxe5 dxe5 7.Qxd8+ Kxd8 8.Nf3
Nbd7 9.b4 a5) (4... h6 {+0.66 pws Stockfish 14.1 64-bmi2} 5.Nf3 d6 6.d4 exd4 7.exd4 Bb6 8.h3 Nc6 9.Be2 Ne7 10.O-O
O-O 11.Bf4 c6 12.Bd3 d5 13.c5) (4... Be7 {+0.67 pws Stockfish 14.1 64-bmi2} 5.Nf3 Nc6 6.Qb3 O-O 7.Be2 Re8 8.O-O
Bf8 9.Rd1 d6 10.h3 h6 11.d4) (4... Bd6 {+0.75 pws Stockfish 14.1 64-bmi2} 5.d4 O-O 6.Bd3 exd4 7.exd4 Re8+ 8.Nge2
Nc6 9.O-O Bf8 10.d5 Ne5 11.Ng3 Bc5 12.Nge4 Nxe4 13.Nxe4) 5.b4 ?? (5.d4 {+0.27 pws Stockfish 14.1 64-bmi2} exd4
6.exd4 Bb4 7.Nf3 O-O 8.Be2 dxc4 9.Bxc4 c5 10.O-O Nc6 11.dxc5 Qxd1 12.Rxd1 Bxc5 13.Bg5 h6 14.Bh4 g5) (5.cxd5 {+0.14
pws Stockfish 14.1 64-bmi2} Nxd5 6.Nf3 Nc6 7.Be2 O-O 8.O-O h6 9.Qc2 Re8 10.a3 Bf8 11.Bd2 Be6 12.b4 a5 13.b5)
(5.Nxd5 {-0.25 pws Stockfish 14.1 64-bmi2} Nxd5 6.cxd5 Qxd5 7.Nf3 Be6 8.Be2 Nc6 9.a3 Be7 10.Bd2 O-O-O 11.O-O f5
12.Bc3 g5 13.b4) (5.a3 {-0.52 pws Stockfish 14.1 64-bmi2} d4 6.Na4 Be7 7.b4 c6 8.exd4 exd4 9.Be2 O-O 10.Nf3 b5
11.Nc5 a5 12.Bd2 Bxc5 13.bxc5 bxc4 14.dxc4) (5.Nf3 {-0.83 pws Stockfish 14.1 64-bmi2} d4 6.exd4 exd4 7.Ne4 Nxe4
8.dxe4 Nc6 9.Bd3 Bg4 10.a3 a5 11.h3 Bh5 12.g4 Bg6 13.Bf4 Qe7 14.O-O O-O-O) (5.h3 {-0.92 pws Stockfish 14.1
64-bmi2} d4 6.exd4 exd4 7.Ne4 Bb4+ 8.Bd2 a5 9.Ng3 O-O 10.Nf3 Re8+ 11.Be2 Bd6 12.O-O c5 13.Re1 h6 14.Bf1) (5.Rb1
{-1.05 pws Stockfish 14.1 64-bmi2} d4 6.b4 Be7 7.exd4 exd4 8.Na4 a5 9.b5 Bb4+ 10.Bd2 Qe7+ 11.Be2 O-O 12.Nf3 Re8
13.Nxd4) (5.Bd2 {-1.08 pws Stockfish 14.1 64-bmi2} d4 6.Na4 Bd6 7.Be2 O-O 8.exd4 exd4 9.b4 Nc6 10.b5 Ne5 11.c5 Be7
12.Nf3 Nxf3+ 13.Bxf3) (5.Be2 {-1.12 pws Stockfish 14.1 64-bmi2} d4 6.Na4 Bb4+ 7.Bd2 Qe7 8.exd4 Bxd2+ 9.Qxd2 exd4
10.b4 Bd7 11.Nc5 a5 12.Nxd7 Nbxd7 13.bxa5 Ne5 14.Rb1 O-O) (5.Nge2 {-1.23 pws Stockfish 14.1 64-bmi2} d4 6.exd4
exd4 7.Ne4 Nxe4 8.dxe4 Qh4 9.Ng3 Nc6 10.a3 a5 11.Bd3 Ne5 12.f4 Ng4 13.Qf3 Nxh2 14.Qf2 Bd7 15.e5) (5.b4 {-3.13 pws
Stockfish 14.1 64-bmi2} Bxb4 6.Bd2 d4 7.exd4 exd4 8.Ne4 Bxd2+ 9.Qxd2 Qe7 10.Ne2 Nxe4 11.dxe4 Nc6 12.f3 Be6 13.Nxd4
Qh4+ 14.g3 Qf6) Bxb4 (5... Bxb4 {-3.03 pws Stockfish 14.1 64-bmi2} 6.Qb3 Nc6 7.cxd5 Nxd5 8.Bd2 Be6 9.Qb2 Bxc3
10.Bxc3 Qd6 11.a3 Nxc3 12.Qxc3 O-O-O 13.Be2 Bd5 14.Nf3 Bxf3 15.gxf3) (5... Bf8 {-0.71 pws Stockfish 14.1 64-bmi2}
6.a3 a5 7.b5 dxc4 8.Nf3 Nbd7 9.dxc4 Bd6 10.Bb2 Qe7 11.Be2 Nc5 12.Nd5 Nxd5 13.cxd5 Bg4 14.O-O Bxf3 15.Bxf3 e4
16.Be2) (5... Be7 {-0.66 pws Stockfish 14.1 64-bmi2} 6.a3 dxc4 7.Nf3 a5 8.b5 Nbd7 9.dxc4 Bd6 10.Bb2 Qe7 11.Be2 Nc5
12.Nd5 Nxd5 13.cxd5 Bg4 14.O-O Bxf3 15.Bxf3 e4 16.Be2 O-O) (5... Bd6 {+0.01 pws Stockfish 14.1 64-bmi2} 6.c5 d4
7.cxd6 dxc3 8.Qb3 cxd6 9.Qxc3 O-O 10.Bd2 Nc6 11.b5 Ne7 12.Nf3 Be6 13.Be2 a6 14.Qb2 axb5 15.Qxb5 Rxa2) (5... Bg4
{+0.30 pws Stockfish 14.1 64-bmi2} 6.Qa4+ Bd7 7.Qb3 Bd6 8.cxd5 a5 9.bxa5 Rxa5 10.Nf3 O-O 11.Bd2 Na6 12.Be2 b5
13.Ne4 Ra3 14.Qb2 Nxe4 15.dxe4 b4 16.O-O) (5... d4 {+1.42 pws Stockfish 14.1 64-bmi2} 6.bxc5 dxc3 7.Ne2 Na6 8.Ba3
c6 9.Qc2 Bf5 10.Qxc3 Qxd3 11.Qxe5+ Be6 12.Qb2 Qd8 13.Rd1 Qa5+ 14.Qc3 Qxc3+ 15.Nxc3 O-O) (5... Bb6 {+3.59 pws
Stockfish 14.1 64-bmi2} 6.c5 d4 7.Ne4 Nd5 8.cxb6 axb6 9.Nf3 Nxb4 10.Nxe5 Qd5 11.Nf3 f5 12.Ng3 dxe3 13.Bxe3 Rxa2
14.Rxa2 Qxa2) (5... Bxe3 {+3.82 pws Stockfish 14.1 64-bmi2} 6.fxe3 d4 7.exd4 exd4 8.Nce2 Qe7 9.h3 Nc6 10.Nf3 Nxb4
11.Kf2 Bd7 12.Nexd4 O-O-O 13.Kg1 Qd6 14.a3 Nc6) (5...  O-O {+5.19 pws Stockfish 14.1 64-bmi2} 6.bxc5 d4 7.Na4 dxe3
8.Bxe3 Nc6 9.Be2 Qe7 10.Nf3 Rd8 11.O-O e4 12.Nd2 Qe5 13.Re1 exd3 14.Bf3 Nd4 15.Bxd4 Qxd4) (5... Nc6 {+5.21 pws
Stockfish 14.1 64-bmi2} 6.bxc5 d4 7.Na4 Qe7 8.Be2 dxe3 9.Bxe3 Bf5 10.Nf3 Rd8 11.O-O e4 12.Nd2 Qe5 13.Qe1 exd3
14.Bf3 O-O 15.Bxc6 bxc6) 6.g4 ?  (6.Qb3 {-2.95 pws Stockfish 14.1 64-bmi2} Nc6 7.cxd5 Nxd5 8.Bd2 Be6 9.Qb2 Qd6
10.a3 Bxc3 11.Bxc3 Nxc3 12.Qxc3 Bd5 13.Nf3 O-O-O 14.Be2 Bxf3 15.gxf3 Qg6) (6.Bd2 {-3.03 pws Stockfish 14.1
64-bmi2} d4 7.exd4 exd4 8.Ne4 Bxd2+ 9.Qxd2 Qe7 10.Ne2 Nxe4 11.dxe4 Nc6 12.Nf4 Qxe4+ 13.Be2 Bf5 14.O-O) (6.Qa4+
{-6.00 pws Stockfish 14.1 64-bmi2} Nc6 7.Bd2 d4 8.exd4 exd4 9.Ne4 Bxd2+ 10.Nxd2 O-O 11.Be2 Re8 12.Ngf3 Qe7 13.Qd1
Bf5 14.Nb3 Qb4+ 15.Kf1 Qd6 16.Qd2 h6 17.h3 a5 18.Kg1) (6.Ne2 {-7.07 pws Stockfish 14.1 64-bmi2} d4 7.Qa4+ Nc6
8.Rb1 Bxc3+ 9.Nxc3 dxc3 10.Ba3 Nd7 11.Qc2 Ne7 12.d4 exd4 13.exd4 O-O 14.Bd3 Nf6 15.O-O Re8 16.Bxe7 Rxe7 17.Rfe1
Rxe1+ 18.Rxe1 Qxd4) (6.Qc2 {-8.51 pws Stockfish 14.1 64-bmi2} d4 7.Ne2 dxc3 8.Qa4+ Nc6 9.Rb1 Bd6 10.Nxc3 O-O
11.Be2 Ne7 12.O-O a6 13.Bf3 c6 14.Rd1 Qc7 15.Ba3 Bxa3 16.Bxc6 Nxc6 17.Qxa3) (6.Qd2 {-8.57 pws Stockfish 14.1
64-bmi2} d4 7.Nge2 dxc3 8.Nxc3 O-O 9.Rb1 Bd6 10.Be2 c6 11.Bf3 e4 12.Nxe4 Nxe4 13.Bxe4) (6.Nf3 {-9.38 pws Stockfish
14.1 64-bmi2} Bxc3+) (6.Bb2 {-9.38 pws Stockfish 14.1 64-bmi2} d4 7.Qb3 Nc6 8.Nf3 dxc3 9.Bxc3 Bxc3+ 10.Qxc3 Qe7
11.Be2 O-O 12.Qb2 e4 13.O-O exf3 14.Bxf3 Ne5 15.d4 Nxc4) (6.cxd5 {-9.61 pws Stockfish 14.1 64-bmi2} Bxc3+ 7.Bd2
Bxd2+ 8.Qxd2 Qxd5 9.Nf3 Nbd7 10.Ng5 O-O 11.Nxh7 Kxh7 12.O-O-O Nc5 13.Qc2 Kg8 14.d4) (6.d4 {-9.92 pws Stockfish
14.1 64-bmi2} Bxc3+ 7.Bd2 Bxd2+ 8.Qxd2 exd4 9.cxd5 O-O 10.Qxd4 c5 11.dxc6 Qxd4 12.exd4 Re8+ 13.Ne2 Nxc6) (6.g4
{-10.17 pws Stockfish 14.1 64-bmi2} Bxc3+ 7.Bd2 Bxd2+ 8.Qxd2 Bxg4 9.Bg2 O-O 10.Ne2 Bxe2 11.Rb1 c6 12.Rxb7 h6
13.Rg1 Bh5) Nxg4 ?! (6... Bxc3+ {-9.97 pws Stockfish 14.1 64-bmi2} 7.Bd2) (6... d4 {-9.16 pws Stockfish 14.1
64-bmi2} 7.Ne2 dxc3 8.Qa4+ Nc6 9.Rb1 Be7 10.Bg2 O-O 11.Qc2 Nxg4 12.O-O Nb4 13.Rxb4 Bxb4 14.Ng3 Kh8 15.h3)
(6... dxc4 {-7.53 pws Stockfish 14.1 64-bmi2} 7.Bd2 Bxg4 8.Qa4+ Nc6 9.h3 Bf5 10.Bg2 Qd6 11.Nf3 O-O 12.dxc4 Bxc3
13.Bxc3 Ne4 14.Rd1 Nxc3 15.Rxd6 Nxa4) (6... Bxg4 {-7.46 pws Stockfish 14.1 64-bmi2} 7.Qb3 Nc6 8.Bd2 d4 9.Nd5 Bxd2+
10.Kxd2 O-O 11.Bg2 Nxd5 12.cxd5 Ne7 13.Nf3 dxe3+ 14.fxe3 Nxd5 15.Nxe5 Be6 16.Qxb7 Rb8) (6... Nc6 {-7.46 pws
Stockfish 14.1 64-bmi2} 7.Bd2 Bxg4 8.Qb3 d4 9.Nd5 Bxd2+ 10.Kxd2 O-O 11.Bg2 Nxd5 12.cxd5 Ne7 13.Nf3 dxe3+ 14.fxe3
Nxd5 15.Nxe5 Be6 16.Qxb7 Rb8) (6... Na6 {-7.18 pws Stockfish 14.1 64-bmi2} 7.Bd2 Bxg4 8.f3 Be6 9.a3 Be7 10.Nh3
dxc4 11.Ng5 Bf5 12.e4 Bg6 13.Qa4+ c6 14.Qxc4 h6 15.Rg1 Nc5) (6... a5 {-6.53 pws Stockfish 14.1 64-bmi2} 7.Bd2 Bxg4
8.Be2 d4 9.exd4 Qxd4 10.Nb5 Bxd2+ 11.Kxd2 Bxe2 12.Nxc7+ Kd8 13.Nxe2 Qb2+ 14.Ke1 Kxc7 15.Rb1 Qa3 16.Rb3 Qe7 17.Nc3
Nc6) (6... O-O {-6.39 pws Stockfish 14.1 64-bmi2} 7.Bd2 d4 8.Nce2 Bxd2+ 9.Qxd2 dxe3 10.fxe3 Bxg4 11.Ng3 Na6 12.h3
Nh5 13.Qf2 Nxg3 14.Qxg3 Bh5 15.Qxe5) (6... c5 {-6.33 pws Stockfish 14.1 64-bmi2} 7.Bd2 Bxg4 8.Nge2 d4 9.Nd5 dxe3
10.Nxe3 Bxe2 11.Bxe2 Nc6 12.Bf3 Qxd3 13.Bxc6+ bxc6 14.Rg1 Bxd2+ 15.Qxd2) (6... c6 {-6.06 pws Stockfish 14.1
64-bmi2} 7.Bd2 Bxg4 8.Qb3 Na6 9.cxd5 cxd5 10.a3 Be7 11.d4 exd4 12.Bxa6 bxa6 13.Qa4+ Qd7) (6... Nxg4 {-5.75 pws
Stockfish 14.1 64-bmi2} 7.Qb3 Qh4 8.Nh3 Na6 9.cxd5 Nf6 10.a3 Bxc3+ 11.Qxc3 Bxh3 12.Qxe5+ Kd8 13.Bb2 Re8 14.Qg3
Qxg3 15.Bxf6+ gxf6 16.hxg3 Bxf1) 7.Qxg4 ?! (7.Qb3 {-5.30 pws Stockfish 14.1 64-bmi2} Qh4 8.Nh3 Na6 9.cxd5 Nf6
10.a3 Bxc3+ 11.Qxc3 Bxh3 12.Qxe5+ Kd8 13.Bb2 Bxf1 14.Kxf1 Qh5 15.Qxh5 Nxh5) (7.Bd2 {-6.81 pws Stockfish 14.1
64-bmi2} d4 8.Ne4 f5 9.h3 Bxd2+ 10.Qxd2 Nxe3 11.fxe3 fxe4 12.O-O-O Qe7 13.Bg2 exd3 14.exd4 Nc6 15.Bxc6+ bxc6
16.Nf3) (7.Qa4+ {-7.61 pws Stockfish 14.1 64-bmi2} Nc6 8.Ne2 d4 9.Bg2 O-O 10.h3 Bxc3+ 11.Nxc3 dxc3 12.hxg4 Qxd3
13.Qd1 Nb4 14.Qxd3 Nxd3+ 15.Kf1 Rd8 16.Be4 g6) (7.Ne2 {-8.06 pws Stockfish 14.1 64-bmi2} d4 8.Qa4+ Nc6 9.Bg2 Bxc3+
10.Nxc3 dxc3 11.h3 O-O 12.hxg4 Qxd3 13.Qd1 Qxd1+ 14.Kxd1 Bxg4+ 15.Kc2) (7.Qd2 {-9.34 pws Stockfish 14.1 64-bmi2}
d4 8.exd4 exd4 9.Qe2+ Be6 10.Bh3 Bxc3+ 11.Kf1 Qh4 12.Rb1 O-O 13.Rb5 Ne3+ 14.fxe3 Bxh3+ 15.Nxh3 Qxh3+ 16.Qg2)
(7.Qc2 {-9.46 pws Stockfish 14.1 64-bmi2} d4 8.exd4 exd4 9.Qe2+ Be6 10.Bh3 h5 11.Kf1 dxc3 12.Bxg4 hxg4 13.Rb1 Nc6
14.Rxb4 Nxb4 15.Bf4 Nxd3) (7.Bh3 {-9.96 pws Stockfish 14.1 64-bmi2} Bxc3+ 8.Bd2 Bxd2+ 9.Qxd2 O-O 10.a4 Qh4 11.a5
dxc4 12.Bxg4 cxd3 13.Bxc8 Rxc8 14.Qxd3 Qb4+ 15.Ke2) (7.Bb2 {-10.07 pws Stockfish 14.1 64-bmi2} d4 8.Qa4+ Nc6 9.Bg2
dxc3 10.Bxc6+ bxc6 11.Qxb4 cxb2 12.Qxb2 O-O 13.O-O-O Re8 14.Nf3 Qf6 15.h3 Nh6) (7.Nf3 {-10.07 pws Stockfish 14.1
64-bmi2} Bxc3+ 8.Bd2 Bxd2+ 9.Nxd2 Nxe3 10.Qh5 Nc2+ 11.Kd1 Nc6 12.Kxc2 dxc4 13.Nxc4 Qf6 14.Bg2 O-O 15.Bxc6 Qxc6
16.Qxe5 f6) (7.Rb1 {-10.22 pws Stockfish 14.1 64-bmi2} Bxc3+ 8.Bd2 Bxd2+ 9.Qxd2 Nf6 10.h4 O-O 11.a4 Re8 12.Be2 Kh8
13.f4 Ng8 14.h5 b6 15.h6) (7.Qxg4 {-13.40 pws Stockfish 14.1 64-bmi2} Bxc3+ 8.Bd2 Bxd2+ 9.Kxd2 Bxg4 10.Ke1 O-O
11.Be2 Be6 12.Rb1 b6 13.Rd1 c6 14.Nf3 Nd7 15.Rd2 f6 16.cxd5 Bxd5 17.Rg1 Be6 18.Kf1) Bxg4 (7... Bxc3+ {-13.38 pws
Stockfish 14.1 64-bmi2} 8.Bd2 Bxd2+ 9.Kxd2 Bxg4 10.Ke1 O-O 11.Be2 Be6 12.Nf3 dxc4 13.dxc4 Nd7 14.Rg1 f6 15.Rd1 Qe7
16.Nd2 f5 17.Kf1 f4 18.Nf3 fxe3 19.fxe3) (7... Bxg4 {-10.69 pws Stockfish 14.1 64-bmi2} 8.Bd2 dxc4 9.dxc4 Nc6
10.Nd5 Ba3 11.Rb1 Rb8 12.Rb3 Bc5 13.h3 Be6 14.Nf3 O-O 15.Nb4 Na5) (7... O-O {-8.44 pws Stockfish 14.1 64-bmi2}
8.Qd1 Bxc3+ 9.Bd2 Bxa1 10.Qxa1 d4 11.Ne2 Nc6 12.Bg2 dxe3 13.fxe3 Qxd3 14.Rg1 Bg4 15.Nc1 Qf5 16.h3 Bxh3 17.Rf1 Qg6
18.Bxh3) (7... Rf8 {-6.81 pws Stockfish 14.1 64-bmi2} 8.Qd1 Bxc3+ 9.Bd2 Bxa1 10.Qxa1 Nc6 11.Ne2 dxc4 12.d4 exd4
13.Bg2 c3 14.Nxc3 dxc3 15.Bxc3 Qd3 16.Bxc6+ bxc6 17.Bxg7) (7... Rg8 {-6.59 pws Stockfish 14.1 64-bmi2} 8.Qd1 Bxc3+
9.Bd2 Bxa1 10.Qxa1 Nc6 11.Bg2 dxc4 12.Nf3 f6 13.O-O Qxd3 14.Bc3 Bd7 15.Qb2 O-O-O 16.Rb1) (7... g6 {-6.27 pws
Stockfish 14.1 64-bmi2} 8.Qd1 Bxc3+ 9.Bd2 Bxa1 10.Qxa1 Nc6 11.Bg2 d4 12.Ne2 O-O 13.O-O dxe3 14.Bxe3 Re8 15.Nc3 Nd4
16.Ne4 Nc2 17.Qb2 Nxe3 18.fxe3) (7... Kf8 {-6.05 pws Stockfish 14.1 64-bmi2}) (7... g5 {-5.16 pws Stockfish 14.1
64-bmi2} 8.Qd1 Bxc3+ 9.Bd2 Bxa1 10.Qxa1 Nc6 11.Bg2 Be6 12.Ne2 dxc4 13.d4 exd4 14.Bxc6+ bxc6 15.Nxd4 Qd5) (7... Be6
{-1.61 pws Stockfish 14.1 64-bmi2} 8.Qxg7 Bxc3+ 9.Ke2 Rf8 10.Ba3 Nd7 11.Bxf8 Bxa1 12.Ba3 c5 13.Bh3 dxc4 14.Bxe6
cxd3+ 15.Kf1 fxe6 16.Qh8+ Ke7 17.Qxh7+ Kd6 18.Qxd3+ Kc7) (7... Nc6 {-1.50 pws Stockfish 14.1 64-bmi2} 8.Qxg7 Bxc3+
9.Ke2 Rf8 10.Ba3 Bb4 11.cxd5 Bxa3 12.dxc6 Qd6 13.Bh3 Qxc6 14.Qxe5+ Be6 15.Bxe6 fxe6 16.Qh5+ Kd7) 8.Ne2 (8.Bd2
{-10.50 pws Stockfish 14.1 64-bmi2} dxc4 9.dxc4 O-O 10.Be2 Bf5 11.a3 Bc5 12.Nf3 Nd7 13.e4 Bg6 14.O-O c6 15.Rab1)
(8.Bb2 {-12.92 pws Stockfish 14.1 64-bmi2} d4 9.Ne2 O-O 10.O-O-O dxc3 11.Bxc3 Bd6 12.f4 Nc6 13.Rd2 Bxe2 14.Rxe2
exf4 15.d4 fxe3 16.Rxe3 Nb4 17.Kb1 c6) (8.Ne2 {-13.40 pws Stockfish 14.1 64-bmi2} Bxe2) (8.Kd2 {-13.97 pws
Stockfish 14.1 64-bmi2} d4 9.Bb2 Qf6 10.Be2 Qxf2 11.exd4 exd4 12.h3 Bh5 13.a3 Ba5 14.Rf1 Qe3+ 15.Kc2 dxc3 16.Bc1
Bxe2) (8.Rb1 {-14.15 pws Stockfish 14.1 64-bmi2} Bxc3+ 9.Bd2 Bxd2+ 10.Kxd2 dxc4 11.f3 Qd5 12.Kc3 cxd3 13.Bxd3 Be6
14.Rb5 Qxa2 15.Rb2 Qa3+ 16.Kc2 Nc6 17.Bb5 Qxe3 18.Bxc6+ bxc6) (8.h3 {-14.69 pws Stockfish 14.1 64-bmi2} Bxc3+
9.Bd2 Bxa1 10.hxg4 dxc4 11.dxc4 Qd7 12.Ne2 O-O 13.Nc1 Qxg4 14.Nb3 Qe4 15.Rg1 f6 16.Nxa1 Qb1+ 17.Ke2 Qxa1 18.Rg3
Qxa2) (8.Be2 {-15.00 pws Stockfish 14.1 64-bmi2} Bxc3+ 9.Bd2 Bxa1 10.Bxg4 dxc4 11.dxc4 Qd3 12.Ne2 Qxc4 13.Rg1 Qxa2
14.Nc3 Qa5 15.Ne4 Qa3 16.Rg3 g6 17.Nf6+ Kf8 18.Nd7+ Kg7 19.Nxb8 Raxb8) (8.f3 {-16.07 pws Stockfish 14.1 64-bmi2}
Bxc3+ 9.Bd2 Bxa1 10.fxg4 Qh4+ 11.Kd1 dxc4 12.Be2 cxd3 13.Bf3 e4 14.Be1 Qg5 15.Bxe4 Qxg4+ 16.Bf3 Qa4+ 17.Kd2 Qxa2+
18.Kxd3) (8.Bh3 {-17.23 pws Stockfish 14.1 64-bmi2} Bxc3+ 9.Bd2 Bxh3 10.Nxh3 Bxa1 11.Ke2 Bb2 12.Rb1 Ba3 13.Rb5 c6
14.Rxb7 dxc4 15.Bb4 Qxd3+ 16.Kf3 Bb2 17.Kg3) (8.Nf3 {-17.61 pws Stockfish 14.1 64-bmi2} Bxc3+ 9.Nd2 Bxa1 10.Rg1
Bc8 11.Rxg7 Bc3 12.Kd1 Bb4 13.Rg3 c6 14.Kc2 Bf5 15.Nf3 e4 16.Ne5 exd3+ 17.Bxd3) Bf3 (8... Bxe2 {-13.61 pws
Stockfish 14.1 64-bmi2} 9.Bd2 Bxf1 10.Rxf1 dxc4 11.a3 Bf8 12.dxc4 Qd3 13.Nd5 Qxc4 14.Nb4 c5 15.Rc1 Qxc1+ 16.Bxc1
cxb4 17.axb4 Bxb4+ 18.Bd2 Bxd2+ 19.Kxd2) (8... Bf3 {-13.32 pws Stockfish 14.1 64-bmi2} 9.Rb1 Bxc3+ 10.Nxc3 Bxh1
11.Nxd5 b6 12.Bb2 Bxd5 13.cxd5 Qxd5 14.Rc1 c5 15.e4 Qe6 16.f4 Nc6 17.Bxe5 f6 18.Bc3 O-O 19.Bd2 Qxa2 20.Rc4)
(8... d4 {-12.33 pws Stockfish 14.1 64-bmi2} 9.Rg1 Bxe2 10.Kxe2 Bxc3 11.Rb1 Qh4 12.Bg2 Qg4+ 13.f3 Qh4 14.Rxb7 Qxh2
15.Kf2 Qh4+ 16.Ke2 c5 17.Rd1 Qg3 18.Kf1 Nd7 19.Bd2 Bxd2 20.Rxd2 dxe3 21.Re2) (8... dxc4 {-11.69 pws Stockfish 14.1
64-bmi2} 9.a3 Ba5 10.Bd2 cxd3 11.Nc1 Bf5 12.Rg1 O-O 13.e4 Nc6 14.Nxd3 Bg6 15.Rg3 Nd4 16.O-O-O Qe7) (8... Na6
{-11.11 pws Stockfish 14.1 64-bmi2} 9.Bd2 Nc5 10.Nc1 dxc4 11.Rg1 f5 12.h3 Bh5 13.Be2 Bxe2 14.N3xe2 Bxd2+ 15.Kxd2
cxd3 16.Nc3 Qh4 17.Rg3 O-O-O 18.Nb3) (8... Nd7 {-11.11 pws Stockfish 14.1 64-bmi2} 9.Bd2 Nc5 10.Ng3 dxc4 11.Nce4
Nxd3+ 12.Bxd3 Qxd3 13.Bxb4 O-O-O 14.Bd6 cxd6 15.Rc1 Bf3 16.Rg1 Bxe4 17.Nxe4 Qxe4) (8... O-O {-11.08 pws Stockfish
14.1 64-bmi2}) (8... e4 {-10.88 pws Stockfish 14.1 64-bmi2} 9.Rb1 Na6 10.cxd5 exd3 11.Rxb4 Nxb4 12.Nf4 Qf6 13.Bb2
Nxa2 14.Kd2 Nb4 15.Rg1 Bc8 16.Bxd3 O-O 17.Bc4 Bf5) (8... c6 {-10.73 pws Stockfish 14.1 64-bmi2} 9.Bd2 dxc4 10.Rg1
Bxe2 11.Bxe2 cxd3 12.Bf3 O-O 13.Rb1 a5 14.a3 Bxa3 15.Rxb7 Bd6) (8... Nc6 {-10.61 pws Stockfish 14.1 64-bmi2} 9.Bd2
dxc4 10.Rg1 Bf5 11.dxc4 O-O 12.Bg2 Qh4 13.a3 Be7 14.Nd5 Bd6 15.e4 Bg6 16.Rb1 Bxa3 17.Rxb7) 9.Ng1 (9.Rg1 {-13.31
pws Stockfish 14.1 64-bmi2} Bxe2 10.Bb2 Bxf1 11.Kxf1 dxc4 12.Rd1 cxd3 13.Rxg7 Nc6 14.Rg3 f5 15.e4 fxe4 16.Nxe4 Qh4
17.Ng5 O-O-O) (9.Rb1 {-13.34 pws Stockfish 14.1 64-bmi2} Bxc3+ 10.Nxc3 Bxh1 11.cxd5 b6 12.Rb4 O-O 13.Rg4 c6 14.Ba3
Re8 15.d6 c5 16.Ne4 f6 17.Rg1 Bf3) (9.a3 {-13.47 pws Stockfish 14.1 64-bmi2} Bxc3+ 10.Nxc3 Bxh1 11.cxd5 Qh4 12.h3
O-O 13.e4 b6 14.Ne2 c6 15.Ng3 Bf3 16.Nf5 Qd8) (9.Bd2 {-13.94 pws Stockfish 14.1 64-bmi2} Bxh1 10.cxd5 Bf3 11.Ng3
c6 12.Be2 Bg2 13.Rb1 Qa5 14.Nce4 Bxd2+ 15.Nxd2 Bxd5 16.Rxb7 O-O 17.Nf5 Bxa2 18.Rb2 g6 19.Ne7+ Kg7) (9.cxd5 {-14.01
pws Stockfish 14.1 64-bmi2} Bxh1 10.Bd2 Bf3 11.Ng3 c6 12.Be2 Bg2 13.Rb1 Qa5 14.Nce4 Bxd2+ 15.Nxd2 Bxd5 16.Rxb7
Bxa2 17.Bf3) (9.Bb2 {-14.39 pws Stockfish 14.1 64-bmi2} Bxh1 10.O-O-O dxc4 11.dxc4 Nd7 12.Bh3 Bc6 13.Bxd7+ Bxd7
14.Nd5 Bd6 15.c5 Bxc5 16.Bxe5 Ba3+ 17.Bb2) (9.Bg2 {-14.61 pws Stockfish 14.1 64-bmi2} Bxg2 10.Rg1 Bh3 11.Rxg7 dxc4
12.Rg3 Be6 13.dxc4 Qd3 14.Bd2 Nc6 15.e4 Qxc4 16.Rd1 Bxc3 17.Nxc3 Nb4 18.Bg5 Nxa2 19.Nxa2) (9.h3 {-14.79 pws
Stockfish 14.1 64-bmi2} Bxh1 10.a3 Ba5 11.Bd2 dxc4 12.dxc4 O-O 13.Ng3 Bc6 14.Nce4 Bxd2+ 15.Nxd2 Be8 16.Be2 c6
17.Rb1 b6 18.Bf3 Qd3) (9.e4 {-14.84 pws Stockfish 14.1 64-bmi2} dxe4 10.Rb1 exd3 11.Rxb4 dxe2 12.Bxe2 Bxh1 13.Kf1
f6 14.Nd5 Bxd5 15.cxd5 Qxd5 16.Kg1 Qxa2) (9.Kd2 {-15.07 pws Stockfish 14.1 64-bmi2} Bxh1 10.Rb1 Na6 11.Rxb4 Nxb4
12.Ba3 a5 13.Ng3 Bf3 14.cxd5 Nxd5 15.Be2 Bg2 16.Nf5 g6 17.Nxd5 Qxd5) (9.Ng1 {-18.00 pws Stockfish 14.1 64-bmi2}
Bxc3+ 10.Bd2 Bxd2+ 11.Kxd2 Bxh1 12.cxd5 Bxd5 13.Ne2 Qh4 14.Ke1 Qxh2 15.Rc1 Bc6 16.d4 Nd7 17.d5 Bxd5 18.Rxc7 Bc6
19.Nc3 g6 20.Bc4 b6) Bxh1 (9...  Bxc3+ {-18.00 pws Stockfish 14.1 64-bmi2} 10.Bd2 Bxd2+ 11.Kxd2 Bxh1 12.cxd5 Bxd5
13.Ne2 Qh4 14.f4 Qxh2 15.fxe5 Qxe5 16.Nc3 O-O 17.Rb1 Bc6 18.d4 Qh2+ 19.Be2 b6 20.Rb2) (9... Bxh1 {-15.46 pws
Stockfish 14.1 64-bmi2} 10.Bd2 dxc4 11.dxc4 Qh4 12.h3 Na6 13.Be2 O-O-O 14.a3 Bc5 15.Nd5 Qg5 16.Bg4+ Kb8 17.Nb4
Nxb4 18.axb4) (9... dxc4 {-14.46 pws Stockfish 14.1 64-bmi2} 10.Nxf3 Bxc3+ 11.Nd2 Bxa1 12.Nxc4 Qd5 13.Rg1 O-O
14.Bb2 Bxb2 15.Nxb2 Qa5+ 16.Kd1 Qxa2 17.Kc2 Nd7 18.Rg4 Qe6 19.Bh3 b5 20.Rh4 Qc6+ 21.Kd2 Nc5 22.Bf5) (9... c6
{-14.23 pws Stockfish 14.1 64-bmi2} 10.Nxf3 Bxc3+ 11.Nd2 Bxa1 12.Nb3 Bc3+ 13.Bd2 Bxd2+ 14.Nxd2 Qa5 15.cxd5 cxd5
16.a4 Qxa4 17.Bg2 Qa2 18.Ke2 Nc6 19.Bh3 Qa3 20.Rb1 Nb4 21.d4 f6 22.dxe5 fxe5) (9... Nc6 {-13.95 pws Stockfish 14.1
64-bmi2} 10.Nxf3 Bxc3+ 11.Nd2 Bxa1 12.Bg2 Nb4 13.cxd5 f5 14.Ba3 Bc3 15.Ke2 Qg5 16.Bf3 Nxa2 17.d6 c6 18.Nc4 O-O-O
19.Bb2 Bxb2 20.Nxb2 Rxd6) (9... Na6 {-13.85 pws Stockfish 14.1 64-bmi2} 10.Nxf3) (9...  a5 {-13.78 pws Stockfish
14.1 64-bmi2} 10.Nxf3 Bxc3+ 11.Nd2 Bxa1 12.Nb3 Bc3+ 13.Bd2 Bb2 14.Bc1 Bxc1 15.Nxc1 dxc4 16.dxc4 Qh4 17.Be2 Nd7
18.Nb3 O-O-O 19.Nd2 a4 20.Rg1 g6 21.Nf3) (9... Qd6 {-13.76 pws Stockfish 14.1 64-bmi2} 10.Nxf3 Bxc3+ 11.Nd2 Bxa1
12.Bg2 c6 13.cxd5 cxd5 14.Nb3 Bc3+ 15.Bd2 Bxd2+ 16.Kxd2 Nc6 17.Rd1 g6 18.Kc1 O-O-O 19.Bf3 f6 20.Rd2 b5 21.Be2 b4)
(9... O-O {-13.70 pws Stockfish 14.1 64-bmi2} 10.Nxf3 Bxc3+ 11.Nd2 Bxa1 12.Bg2 c6 13.cxd5 cxd5 14.Nb3 Bc3+ 15.Bd2
Bb2 16.Na5 b6 17.Nc4 dxc4 18.dxc4 Nd7 19.Bxa8 Qxa8 20.O-O) (9... a6 {-13.69 pws Stockfish 14.1 64-bmi2} 10.Nxf3
Bxc3+ 11.Nd2 Bxa1 12.Nb3 Bc3+ 13.Bd2 Bb2 14.Bc1 Bxc1 15.Nxc1 dxc4 16.dxc4 Nd7 17.Bg2 c6 18.Nb3 O-O 19.O-O f5
20.Rc1 Ra7 21.Re1 a5 22.Nd2 a4 23.Nf3 a3) 10.h4 ?! (10.Bd2 {-15.76 pws Stockfish 14.1 64-bmi2} dxc4 11.dxc4 Na6
12.Nge2 Bf8 13.Ng3 Bf3 14.Be2 Bg2 15.Bf1 Bxf1 16.Nxf1 Nb4 17.Ke2 Qd3+ 18.Kf3 Qxc4) (10.Ne2 {-16.96 pws Stockfish
14.1 64-bmi2} d4 11.Rb1 Bxc3+ 12.Nxc3 dxc3 13.Rb3 c5 14.a3 c2 15.Rc3 e4 16.Rxc2 exd3 17.Rd2 Be4 18.Bb2 f6 19.Bc3
Qb6) (10.Bb2 {-17.18 pws Stockfish 14.1 64-bmi2} d4 11.a3 Bxc3+ 12.Bxc3 dxc3 13.Rc1 Na6 14.Rxc3 Nc5 15.Be2 Qf6
16.Rc2 Qc6 17.Bf1 O-O 18.Rc3 f6 19.Ne2 Bf3) (10.Kd2 {-18.15 pws Stockfish 14.1 64-bmi2} d4 11.Bb2 Qh4 12.Nh3 Nc6
13.a3 dxc3+ 14.Bxc3 Bc5 15.Rb1 O-O-O 16.Bb4 Qxc4 17.Bxc5 Qxc5 18.Rb3 Qc4 19.Rb2 f6 20.f4) (10.Rb1 {-18.80 pws
Stockfish 14.1 64-bmi2} Bxc3+ 11.Bd2 Bxd2+ 12.Kxd2 dxc4 13.Rb5 Qf6 14.f3 Qg5 15.Ne2 Bxf3 16.Nd4 c3+ 17.Kc2 Bh5
18.Be2 exd4 19.Rxg5 Bxe2 20.Rxg7) (10.Kd1 {-19.94 pws Stockfish 14.1 64-bmi2} Bxc3) (10.Bg2 {-20.61 pws Stockfish
14.1 64-bmi2} Bxg2 11.Bd2 dxc4 12.Nce2 cxd3 13.Bxb4 dxe2 14.Nxe2 Na6 15.Ba5 Qd3 16.Rd1 Qc2 17.Rc1 Qb2 18.Bc3 Qxa2)
(10.Nf3 {-22.30 pws Stockfish 14.1 64-bmi2} Bxc3+ 11.Nd2 Bxa1 12.Nb3 Bc3+ 13.Bd2 Bb2 14.Bc1 Bxc1 15.Nxc1 Qh4
16.cxd5 Bxd5 17.e4 Be6 18.Ne2 Qxh2 19.Nc3 Nd7 20.Nd5 O-O-O) (10.Ke2 {-23.05 pws Stockfish 14.1 64-bmi2} Bxc3
11.Bb2 dxc4 12.Rd1 Bxb2 13.dxc4 Qh4 14.Kd3 Qxf2 15.Be2 Qxh2 16.Rb1 Ba3 17.Kc2) (10.cxd5 {-23.15 pws Stockfish 14.1
64-bmi2} Bxc3+ 11.Bd2 Bxa1 12.Ne2 Qxd5 13.Ng3 Bf3 14.Be2 Bg2 15.Bf1 Bxf1 16.Nxf1 Qxd3 17.f4 Qb1+ 18.Kf2 Qxa2
19.Kg3 b6) (10.h4 {-24.00 pws Stockfish 14.1 64-bmi2} Bxc3+ 11.Bd2 Bxa1 12.h5 dxc4 13.dxc4 e4 14.Ne2 Qd3 15.Nc1
Qb1 16.f4 Bb2 17.Kf2 Bxc1 18.Bxc1 Qxc1 19.f5 Qc2+ 20.Kg1) Bxc3+ (10... Bxc3+ {-24.30 pws Stockfish 14.1 64-bmi2}
11.Bd2 Bxa1 12.h5 dxc4 13.dxc4 e4 14.Nh3 Nd7 15.h6 Ne5 16.Be2 gxh6 17.a4 Qd7 18.Nf4 O-O-O 19.Nd5 c6 20.Bc3 Bxc3+
21.Nxc3 Qd2+ 22.Kf1) (10... d4 {-18.73 pws Stockfish 14.1 64-bmi2} 11.Rb1 Bxc3+ 12.Bd2 dxe3 13.Bxc3 exf2+ 14.Kxf2
Qxh4+ 15.Ke2 Qh2+ 16.Kd1 Qxg1 17.Kc2 Nc6 18.Be2 Qf2 19.Kd1 b6 20.Rb2 Qg2 21.Be1 a5 22.Kc1) (10... dxc4 {-17.51 pws
Stockfish 14.1 64-bmi2} 11.Bd2 cxd3 12.Ne4 Bf8 13.Ng3 Bc6 14.Rc1 Na6 15.Rxc6 bxc6 16.Bg2 Nb4 17.Kf1 Nd5 18.Nf3 f6
19.h5 g6 20.hxg6) (10... Qxh4 {-16.67 pws Stockfish 14.1 64-bmi2} 11.Bd2 dxc4 12.dxc4 Na6 13.Nge2 O-O-O 14.Ng3 Bf3
15.a3 Bf8 16.Be2 Bxe2 17.Ncxe2 Nc5 18.Bb4 Nd3+ 19.Kf1 c5 20.Bc3 Qxc4 21.Kg1 b6) (10... Na6 {-16.65 pws Stockfish
14.1 64-bmi2} 11.Bd2 dxc4 12.dxc4 Qxh4 13.Nge2 O-O-O 14.Ng3 Bf3 15.Rb1 f6 16.Rb3 Qg4 17.e4 Bc5 18.Nf5 Qg1 19.Ne3
c6) (10... Nc6 {-16.44 pws Stockfish 14.1 64-bmi2} 11.Bd2 dxc4 12.dxc4 Qxh4 13.Nge2 O-O-O 14.Ng3 Bf3 15.Rb1 f6
16.Nd5 Bf8 17.Rc1 Qh2 18.Be2 Qg1+ 19.Nf1 Bxd5 20.cxd5) (10... b6 {-16.21 pws Stockfish 14.1 64-bmi2} 11.Bd2 dxc4
12.dxc4 Qxh4 13.Nge2 Na6 14.Ng3 Bb7 15.Nd5 Bf8 16.Be2 c6 17.Nc3 g6 18.O-O-O Ba3+ 19.Kc2 f5 20.Be1) (10... Nd7
{-16.12 pws Stockfish 14.1 64-bmi2} 11.Bd2 dxc4 12.dxc4 Qxh4 13.Nge2 O-O-O 14.Ng3 Bf3 15.Nd5 Bf8 16.Ba5 b6 17.Bb4
c5 18.Bd2 Qg4 19.Rc1 Qe6 20.Be2 Bxd5 21.cxd5 Qxd5 22.Rc4) (10... g6 {-16.12 pws Stockfish 14.1 64-bmi2} 11.Bd2
dxc4 12.dxc4 Qxh4 13.Nd5 Bxd2+ 14.Kxd2 Na6 15.Nh3 c6 16.Nc3 Nc5 17.Ke1 O-O 18.Nb1 Qd8 19.Nc3 f6 20.Rc1 b6 21.Rd1)
(10... O-O {-15.99 pws Stockfish 14.1 64-bmi2} 11.Bd2 dxc4 12.dxc4 Qxh4 13.a3 Bc5 14.Nd5 Nc6 15.Ne2 Qxc4 16.Nxc7
Rad8 17.Nd4 Bxd4 18.Bxc4 Bxa1 19.Nb5 g6 20.Ke2 Bd5 21.Bxd5 Rxd5 22.Nc7) 11.Bd2 (11.Bd2 {-24.64 pws Stockfish 14.1
64-bmi2} Bxa1 12.Ne2 dxc4 13.d4 exd4 14.Nxd4 Qd5 15.f4 c3 16.Bc1 Qxa2 17.Bd3 O-O 18.Bf5 c6 19.Bc2 Rd8) (11.Kd1
{-25.73 pws Stockfish 14.1 64-bmi2} Bxa1) (11.Ke2 {-26.87 pws Stockfish 14.1 64-bmi2} dxc4 12.Kd1 Bxa1 13.Bd2 cxd3
14.a4 e4 15.Ke1 Qxh4 16.Nh3 Nc6 17.Kd1 Be5 18.Be1 b6 19.Kc1 f5 20.Kb1) Bxa1 (11... Bxa1 {-24.59 pws Stockfish 14.1
64-bmi2} 12.Ne2 dxc4 13.dxc4 Qxh4 14.Ng3 Bc6 15.Bb4 Nd7 16.Nf5 Qf6 17.Bh3 a5 18.Bd2 Nc5 19.Kf1 g6 20.Ng3)
(11... Bxd2+ {-19.79 pws Stockfish 14.1 64-bmi2} 12.Kxd2 dxc4 13.Be2 Bc6 14.Rc1 cxd3 15.Bf3 e4 16.Rxc6 bxc6
17.Bxe4 Qxh4 18.Kxd3 Qxf2 19.Ne2 f5 20.Bxf5 Qxf5+ 21.Kd2 Qd5+ 22.Ke1 Qxa2 23.Nf4) (11... Bb2 {-18.25 pws Stockfish
14.1 64-bmi2}) (11... d4 {-17.46 pws Stockfish 14.1 64-bmi2} 12.Bxc3 dxc3 13.Rc1 Qxh4 14.Rxc3 Bc6 15.Bh3 Qh5
16.Rc1 e4 17.dxe4 Qa5+ 18.Kf1 Bxe4 19.Bg2 Qd2 20.Ne2 Bxg2+ 21.Kxg2 Qxe2) (11... Bd4 {-15.83 pws Stockfish 14.1
64-bmi2} 12.exd4 dxc4 13.dxc4 Qxd4 14.Rc1 Qxh4 15.Rc3 Nd7 16.Ne2 Bc6 17.Rg3 Qxc4 18.Nc3 Qe6 19.Nb5 Kd8 20.Nc3 b6
21.Rxg7 f6 22.Ba6) (11... dxc4 {-15.76 pws Stockfish 14.1 64-bmi2} 12.Bxc3 cxd3 13.Bxe5 Nc6 14.Bc3 O-O 15.h5 Re8
16.O-O-O Be4 17.f3 Bf5 18.Bd2 g6 19.hxg6) (11... Qxh4 {-15.37 pws Stockfish 14.1 64-bmi2} 12.Bxc3 dxc4 13.dxc4 Nd7
14.Rc1 O-O-O 15.Bb4 g6 16.Ne2 Kb8 17.Ng3 Bc6 18.Be2 f5 19.Kf1) (11... Nc6 {-15.37 pws Stockfish 14.1 64-bmi2}
12.Bxc3 dxc4 13.dxc4 Qxh4 14.Bd2 Be4 15.Ne2 Bg6 16.Rd1 O-O-O 17.Ng3 Qh2 18.Be2 f6 19.Rc1 b6 20.Bc3 Qg1+ 21.Bf1)
(11... Bb4 {-15.23 pws Stockfish 14.1 64-bmi2} 12.Bxb4 dxc4 13.dxc4 Qxh4 14.Rc1 Nd7 15.Ne2 g6 16.Nc3 O-O-O 17.Be2
Kb8 18.Ba3 Bc6 19.Nd5 Bxd5 20.cxd5 Qh1+ 21.Bf1) (11... Nd7 {-15.23 pws Stockfish 14.1 64-bmi2} 12.Bxc3 Qxh4
13.cxd5 Bxd5 14.d4 f6 15.Ne2 c5 16.dxe5 fxe5 17.Ng3 O-O-O 18.Be2 b6 19.Kf1 Qg5 20.Kg1) 12.cxd5 (12.Ne2 {-24.57 pws
Stockfish 14.1 64-bmi2} dxc4 13.dxc4 Qxh4 14.Ng3 Bc6 15.Kd1 Nd7 16.Be1 g6 17.Kc2 Qf6 18.Ne2 Nc5 19.Nc3 e4 20.Nb5)
(12.h5 {-24.61 pws Stockfish 14.1 64-bmi2} dxc4 13.dxc4 e4 14.Be2 Nd7 15.Nh3 Ne5 16.h6 g6 17.Nf4 c6 18.c5 Nd7
19.Nd5 cxd5 20.Bb5) (12.a3 {-24.61 pws Stockfish 14.1 64-bmi2} dxc4 13.dxc4 Qxh4 14.Ne2 Qe4 15.Nc1 Qc2 16.Bd3 Qa4
17.Na2 c6 18.Nb4 Qxa3 19.Kf1 a5) (12.cxd5 {-24.69 pws Stockfish 14.1 64-bmi2} Qxd5 13.a3 Qb3 14.f3 Qb1+ 15.Ke2 Nc6
16.h5 Rd8 17.Kf2 Qb2 18.Ke1 Qxa3 19.Be2 Qe7) (12.Be2 {-24.76 pws Stockfish 14.1 64-bmi2} dxc4 13.dxc4 Qxh4 14.Bd1
Qe4 15.Ne2 Qxc4 16.Bb3 Qd3 17.Nc1 Qb1 18.Bd1 g6 19.Ne2 Qxa2) (12.c5 {-25.23 pws Stockfish 14.1 64-bmi2} Qxh4
13.Ne2 Bf3 14.Ng3 Nd7 15.c6 bxc6 16.e4 Qh2 17.Be2 Qg1+ 18.Nf1 Bg2 19.Bb4 dxe4) (12.a4 {-25.35 pws Stockfish 14.1
64-bmi2} dxc4 13.dxc4 Qxh4 14.Ne2 Qe4 15.Nc1 Qc2 16.f3 Bxf3 17.Be2 Bc6 18.a5 Be4) (12.d4 {-25.53 pws Stockfish
14.1 64-bmi2} exd4 13.Ne2 dxe3 14.Bxe3 dxc4 15.Bg5 f6 16.Bd2 Bf3 17.Nc1 c3 18.Bb5+ c6) (12.Ba5 {-25.70 pws
Stockfish 14.1 64-bmi2} dxc4 13.dxc4 Qxh4 14.Ne2 Qe4 15.f4 Qxe3 16.Bd2 Qf3 17.Nc1 Qe4+ 18.Be2 exf4) (12.Nh3
{-26.04 pws Stockfish 14.1 64-bmi2} dxc4 13.h5 cxd3 14.h6 gxh6 15.a4 Nc6 16.f4 Qh4+ 17.Kd1 Bf3+ 18.Kc1 f6 19.Ng1)
Qxd5 (12... Qxd5 {-25.00 pws Stockfish 14.1 64-bmi2} 13.f3 Qxa2 14.Be2 Bg2 15.f4 Nc6 16.Nf3 exf4 17.e4 Bf6 18.Bxf4
Bxf3 19.Bxf3 Bxh4+ 20.Kd1 Qf2 21.Bxc7 Qxf3+ 22.Kc2) (12... Qxh4 {-24.51 pws Stockfish 14.1 64-bmi2} 13.Ne2 Qa4
14.f4 Qc2 15.d4 exd4 16.Nxd4 Qb1+ 17.Kf2 Qxa2 18.Ke1 Qb1+ 19.Kf2) (12... O-O {-23.98 pws Stockfish 14.1 64-bmi2}
13.Ne2 Qxh4 14.d6 cxd6 15.Ng3 Bd5 16.Ne4 Bxa2 17.Nxd6 Bb3 18.Be2 Qh1+ 19.Bf1 Qc6) (12... Bxd5 {-23.84 pws
Stockfish 14.1 64-bmi2} 13.h5 Qe7 14.a4 Nc6 15.a5 Rd8 16.Ne2 Qa3 17.Ng3 g6 18.hxg6 hxg6) (12... Qe7 {-23.84 pws
Stockfish 14.1 64-bmi2} 13.Be2 Qf6 14.Bd1 Qg6 15.Ne2 Qxd3 16.Bb3 Bg2 17.Ba4+ Kf8 18.Bb3 Kg8 19.h5 b6) (12...  Qd6
{-23.76 pws Stockfish 14.1 64-bmi2} 13.Ne2 Qa3 14.Nc1 Bxd5 15.h5 Bb2 16.h6 gxh6 17.e4 Be6 18.Kd1 f5 19.exf5 Bxf5
20.Bxh6) (12... c6 {-23.76 pws Stockfish 14.1 64-bmi2} 13.Ne2 Bxd5 14.Nc1 Qxh4 15.Nb3 Bb2 16.e4 Bxb3 17.axb3 Bd4
18.Be2 Qxf2+ 19.Kd1 Qg1+ 20.Kc2 Qg2 21.Kd1 Nd7 22.Bc1 O-O-O 23.Kd2) (12... Qf6 {-23.69 pws Stockfish 14.1 64-bmi2}
13.Ne2 Qb6 14.Nc1 Qb1 15.f3 Bxf3 16.e4 f5 17.Be2 Bh1 18.exf5 O-O 19.Bd1 Bb2 20.Bb3 Qxc1+ 21.Bxc1 Bxc1) (12... f5
{-23.61 pws Stockfish 14.1 64-bmi2} 13.Ne2 Qxh4 14.a3 Qa4 15.Ng3 Bf3 16.Be2 Bxd5 17.Nxf5 Kf7 18.e4 Be6) (12... a5
{-23.53 pws Stockfish 14.1 64-bmi2} 13.Ne2 Qxh4 14.Nc1 Bxd5 15.Nb3 Bb2 16.e4 Bxb3 17.axb3 Bd4 18.Be2 Qxf2+ 19.Kd1
Qg1+ 20.Kc2 Qg2 21.Kd1 c6 22.b4 Qg1+ 23.Kc2 axb4) 13.a4 (13.a3 {-25.07 pws Stockfish 14.1 64-bmi2} Qb3 14.f3 Qxa3
15.h5 Qe7 16.Nh3 Bxf3 17.Be2 Bc6 18.Bg4 Bb2 19.Nf2 g6) (13.f4 {-25.25 pws Stockfish 14.1 64-bmi2} exf4 14.Ne2 fxe3
15.Bxe3 Qxd3 16.Bf4 Qc2 17.Kf2 Bd5 18.Ke1 f6 19.Kf2 Bb2 20.Be3 Bxa2) (13.a4 {-25.30 pws Stockfish 14.1 64-bmi2}
Qb3 14.f3 Qxa4 15.Bh3 Qc2 16.Bf1 Qa2 17.Ne2 Bxf3 18.Ng1 Bd5 19.Be2 Qb1+ 20.Kf2) (13.Ne2 {-25.35 pws Stockfish 14.1
64-bmi2} Qxa2 14.f3 Bxf3 15.Ng1 Bd5 16.Be2 Qb1+ 17.Kf2 Qc2 18.Be1 Nc6 19.e4 Bb3 20.Nf3 g6 21.Nd2) (13.f3 {-25.35
pws Stockfish 14.1 64-bmi2} Qxa2 14.Ne2 Bxf3 15.Ng1 Bd5 16.Be2 Qb1+ 17.Kf2 Qc2 18.Be1 Nc6 19.e4 Be6 20.Nf3 g6
21.Nd2) (13.d4 {-25.35 pws Stockfish 14.1 64-bmi2} Qxa2 14.Bb5+ Kf8 15.Bd3 Qb3 16.Be2 Qb1+ 17.Bd1 Nc6 18.Ne2 exd4
19.exd4 Re8 20.Be3 f6) (13.h5 {-25.66 pws Stockfish 14.1 64-bmi2} Qxa2 14.f3 Nc6 15.Ne2 Bxf3 16.Nc1 Qb1 17.Be2 Bd5
18.Bg4 f6 19.h6 g6 20.e4 Bf7) (13.Kd1 {-25.92 pws Stockfish 14.1 64-bmi2} Qxa2 14.f3 Nc6 15.h5 Qb1+ 16.Ke2 O-O-O
17.Kf2 e4 18.dxe4 Rxd2+ 19.Ne2 Bf6 20.Bh3+ Kb8) (13.Nh3 {-26.54 pws Stockfish 14.1 64-bmi2} Qxa2 14.Ng1 Qb1+
15.Ke2 Nc6 16.f3 Qc2 17.Ke1 e4 18.d4 exf3 19.Nxf3 Bxf3 20.Bb5 Qd1+ 21.Kf2 Qxd2+ 22.Kxf3 Qd1+ 23.Kg3 Qe1+ 24.Kf3)
(13.Be2 {-26.69 pws Stockfish 14.1 64-bmi2} Qg2 14.Bf3 Qxf3 15.Nxf3 Bxf3 16.Bc1 Nc6 17.Kd2 O-O-O 18.a3 Be4 19.Bb2
Bxb2 20.Kc2) Qa2 ! (13... Qa2 {-25.92 pws Stockfish 14.1 64-bmi2} 14.f3 Qxa4 15.Ke2 Nc6 16.h5 Qc2 17.Ke1 e4
18.dxe4 Bf6 19.Bh3 Qb1+ 20.Kf2 Bh4+ 21.Ke2) (13... Qb3 {-25.70 pws Stockfish 14.1 64-bmi2} 14.f3 Qxa4 15.d4 exd4
16.Bd3 dxe3 17.Bxe3 Qxh4+ 18.Kd1 Qa4+ 19.Bc2 Qa3 20.Ke2 g6 21.Be4 f5 22.Bd3 Nc6) (13... Nd7 {-25.15 pws Stockfish
14.1 64-bmi2} 14.Ne2) (13... Nc6 {-25.05 pws Stockfish 14.1 64-bmi2} 14.a5 Qb3 15.f3 Qb1+ 16.Kf2 Qc2 17.Ke1 e4
18.fxe4 Qb1+ 19.Kf2 Qd1 20.Be1 Bf6 21.Ne2) (13... O-O {-24.89 pws Stockfish 14.1 64-bmi2} 14.a5 Nc6 15.h5 Qb3
16.f3 Qa4 17.Nh3 Bxf3 18.Be2 Bxe2 19.Kxe2 Qg4+ 20.Kf2 Qxh3 21.Be1 Qxh5) (13... a6 {-24.75 pws Stockfish 14.1
64-bmi2} 14.h5 Nc6 15.h6 gxh6 16.f4 exf4 17.exf4 Bf6 18.Be3 Qb3 19.Nh3 Qxa4 20.Nf2) (13... h6 {-24.72 pws
Stockfish 14.1 64-bmi2} 14.Nh3 Qb3 15.f4 Bf3 16.Be2 Qb1+ 17.Kf2 Qc2 18.Ng1 Qxd2 19.Nxf3 Qc2 20.Nxe5 Bc3 21.Kg3
Qxa4) (13... a5 {-24.69 pws Stockfish 14.1 64-bmi2} 14.h5 Nc6 15.f4 Qd8 16.Nh3 Qh4+ 17.Ke2 Bd5 18.fxe5 Nxe5 19.Nf2
Bf3+ 20.Ke1 Bxh5) (13... f5 {-24.69 pws Stockfish 14.1 64-bmi2} 14.a5 O-O 15.h5 Qb3 16.f3 Nc6 17.Be2 Qb1+ 18.Kf2
Qc2 19.Ke1 f4 20.h6) (13... b6 {-24.38 pws Stockfish 14.1 64-bmi2} 14.a5 bxa5 15.Nh3 Nc6 16.Ng5 f5 17.f4 exf4
18.exf4 h6 19.Nh3 Bf6) 14.a5 (14.f3 {-25.47 pws Stockfish 14.1 64-bmi2} Qxa4 15.Ke2 Qxh4 16.Bh3 Qg3 17.Kf1 Bxf3
18.Be1) (14.e4 {-27.03 pws Stockfish 14.1 64-bmi2} Qb1+ 15.Ke2 Nc6 16.f4 Bd4 17.Nh3 Bf3+ 18.Kxf3 Qd1+ 19.Be2 Qxd2
20.fxe5 Nxe5+ 21.Kg2 Nxd3 22.Ng5) (14.Be2 {-27.07 pws Stockfish 14.1 64-bmi2} Qb1+ 15.Bd1 Nc6 16.Ne2 Qxd3 17.Ng3
Rd8 18.Nxh1 Qxd2+ 19.Kf1 Qd5 20.Ng3 Qc4+ 21.Kg1 e4) (14.a5 {-27.22 pws Stockfish 14.1 64-bmi2} Qb1+ 15.Ke2 Bd5
16.f4 e4 17.Kf2 exd3 18.Bg2 Qd1 19.Bxd5 Qxd2+ 20.Kf3 Nc6) (14.Kd1 {-27.33 pws Stockfish 14.1 64-bmi2} Qb1+ 15.Ke2
Bd5 16.Ba5 Qc2+ 17.Ke1 Nc6 18.Bd2 Qb1+ 19.Ke2 e4 20.dxe4 Bc4+ 21.Kf3 Qxf1 22.Kg3 Qxg1+ 23.Kf3) (14.h5 {-27.53 pws
Stockfish 14.1 64-bmi2} Qb1+) (14.Bh3 {-27.92 pws Stockfish 14.1 64-bmi2} Qb1+ 15.Ke2 Qxg1 16.h5 e4 17.dxe4 Nc6
18.Bd7+ Kxd7 19.h6 Bxe4) (14.Ne2 {-28.48 pws Stockfish 14.1 64-bmi2} Bf3 15.Bg2 Qb1+ 16.Nc1 Bc3 17.Kf1 Bxd2
18.Bxf3 Qxc1+ 19.Kg2 a5 20.Bxb7) (14.d4 {-28.62 pws Stockfish 14.1 64-bmi2} Qb1+ 15.Ke2 Bd5 16.Ba5 exd4 17.e4 Bc3
18.exd5 Bxa5 19.Kf3 Qf5+ 20.Kg2 Qg4+ 21.Kh2 Qxh4+ 22.Kg2) (14.f4 {-28.69 pws Stockfish 14.1 64-bmi2} Qb1+ 15.Ke2
exf4 16.h5 f3+ 17.Kf2 Qc2 18.h6 Qxd2+ 19.Be2 Bc3 20.Nxf3 Bxf3 21.hxg7 Qxe2+ 22.Kg3 Be5+ 23.Kh4 Bxg7) Qb1+
(14... Qb1+ {-28.44 pws Stockfish 14.1 64-bmi2}) (14... Na6 {-27.87 pws Stockfish 14.1 64-bmi2} 15.f4 Qb1+ 16.Kf2
Qd1 17.Bc1 Qxc1 18.Ne2 Qd2 19.fxe5 Qxd3 20.Nd4 Qd2+ 21.Be2) (14... Nd7 {-27.18 pws Stockfish 14.1 64-bmi2} 15.f3
Nc5 16.a6 bxa6 17.Kd1 Qb3+ 18.Ke1 Qb1+ 19.Kf2 Qc2 20.Ke2 Qxd3+ 21.Ke1 Qb1+ 22.Kf2 Qc2) (14... e4 {-26.87 pws
Stockfish 14.1 64-bmi2} 15.d4 Qb1+ 16.Ke2 Nc6 17.a6 Bxd4 18.exd4 Nxd4+ 19.Ke3 Qxf1 20.Kxd4 Rd8+ 21.Kc3 Qa1+ 22.Kc2
Qxg1 23.axb7 Qxf2 24.Kc3 Bf3 25.Kc4 Qxh4 26.Be3) (14... Nc6 {-26.23 pws Stockfish 14.1 64-bmi2} 15.f3 Qb1+ 16.Kf2
e4 17.d4 Qd1 18.Be1 exf3 19.Nh3 Nxd4 20.Bb4 Nc2 21.Bc5 Qd2+ 22.Kg1 Qe1) (14... O-O {-25.53 pws Stockfish 14.1
64-bmi2} 15.f3 Qa4 16.Ke2 Qxh4 17.Be1 Qh2+ 18.Bf2 Nc6 19.a6 bxa6 20.Nh3 f6 21.Ng1 Rad8 22.Ke1 f5 23.Ke2)
(14... Qb3 {-25.27 pws Stockfish 14.1 64-bmi2} 15.f3 Qa4 16.Bh3 Qxh4+ 17.Kf1 Qg3 18.Be1 Qg5 19.Bd2 Qg6 20.Kf2 Qxd3
21.Be1 e4 22.Ne2 Bf6 23.fxe4 Qxe4) (14... Bb2 {-25.02 pws Stockfish 14.1 64-bmi2} 15.f3 Qa4 16.Nh3 Bxf3 17.Be2
Qxh4+ 18.Nf2 Bc6 19.Bd1 h5 20.Ke2 Qh2 21.Bb3 Qg2 22.Ke1 g6 23.Nd1) (14... Qc2 {-25.00 pws Stockfish 14.1 64-bmi2}
15.f3 Qa4 16.Bh3 Qxh4+ 17.Kf1 Qg3 18.Be1 Qg5 19.Bf2 Qg6 20.Ke2 Nc6 21.a6 Rd8 22.e4 Qd6 23.Bh4 Qxd3+ 24.Kf2)
(14... g6 {-24.82 pws Stockfish 14.1 64-bmi2} 15.f3 Qa4 16.e4 Nc6 17.h5 Bd4 18.Ne2 Qa1+ 19.Nc1 Nxa5 20.Ke2 Nc6
21.f4 gxh5 22.fxe5 Nxe5 23.Bg5) 15.Ke2 (15.Ke2 {-29.32 pws Stockfish 14.1 64-bmi2} Bd5 16.f3 Bb3 17.Bb4 Bd1+
18.Kf2 Qxb4 19.Be2 Qd2 20.Kf1 Qxe3 21.Bxd1 Bd4 22.Nh3 Kf8 23.Be2 h6 24.Kg2 f6 25.Kf1 Qd2 26.Nf2 Qf4 27.Kg2 Qxh4
28.Nh1 Nc6 29.Ng3 Nxa5) (15.Bc1 {M-3 Stockfish 14.1 64-bmi2} Qxc1+ 16.Ke2 Qc2+ 17.Ke1 Bc3#) Nc6 (15... Bd5 {-29.24
pws Stockfish 14.1 64-bmi2} 16.f3 Bb3 17.Bb4 Bd1+ 18.Kf2 Qxb4 19.Be2 Qd2 20.Kf1 Qxe3 21.Bxd1 Kf8 22.Nh3 Bd4 23.Be2
f6 24.Ke1 Qc1+ 25.Bd1 Nc6 26.Kf1 Qd2 27.Be2 Qxa5 28.Kg2) (15... Qa2 {-28.94 pws Stockfish 14.1 64-bmi2} 16.Kd1
Qb1+ 17.Ke2 Bd5 18.f3 Bb3 19.Bb4 Bd1+ 20.Kf2 Qxb4 21.Be2 Qd2 22.Kf1 Qxe3 23.Bxd1 Kf8 24.Be2 f6 25.Nh3 Qh6 26.Kg2
Qxh4 27.Nf2 Qb4) (15... Qc2 {-28.76 pws Stockfish 14.1 64-bmi2} 16.Ke1 Qb1+ 17.Ke2 Bd5 18.f3 Bb3 19.Bb4 Bd1+
20.Kf2 Qxb4 21.Be2 Qd2 22.Kf1 Qxe3 23.Bxd1 Bd4 24.Nh3 Kf8 25.Be2 f6 26.h5 Bc3 27.Nf2 Qc1+ 28.Kg2 Bxa5) (15... Bc6
{-28.69 pws Stockfish 14.1 64-bmi2}) (15... Na6 {-28.25 pws Stockfish 14.1 64-bmi2} 16.f3 Nc5 17.a6 Qxd3+ 18.Ke1
Qb1+ 19.Kf2 Qb2 20.Ke1 bxa6 21.Be2 O-O-O 22.Ba5 Qa2 23.Kf1 Qxa5 24.Nh3 Qd2 25.Ng5) (15... Nc6 {-27.61 pws
Stockfish 14.1 64-bmi2} 16.f3 e4 17.d4 exf3+ 18.Nxf3 Qe4 19.Ng5 Nxd4+ 20.Ke1 Qxh4+ 21.Kd1 Nb3 22.Bd3 Qxg5 23.a6
bxa6) (15... Nd7 {-27.49 pws Stockfish 14.1 64-bmi2} 16.f3 Nc5 17.a6 Qxd3+ 18.Ke1 Qb1+ 19.Kf2 Qb2 20.Ke1 bxa6
21.Ba5 Qa2 22.Bb4 Qb1+ 23.Kf2 Qxb4) (15... e4 {-27.46 pws Stockfish 14.1 64-bmi2} 16.d4 Nc6 17.a6 Rd8 18.f3 exf3+
19.Nxf3 Qe4 20.h5 Bxf3+ 21.Kf2 Qc2 22.axb7 Qxd2+ 23.Kxf3) (15... Qb3 {-26.12 pws Stockfish 14.1 64-bmi2} 16.h5 Qc2
17.Ke1 Qb1+ 18.Ke2 Bd5 19.f4 e4 20.Nh3 exd3+ 21.Kf2 Qd1 22.Be1 Qxh5) (15... O-O {-25.71 pws Stockfish 14.1
64-bmi2} 16.f3 e4 17.fxe4 Qc2 18.Ke1 Bf6 19.Nh3 Bxh4+ 20.Ke2 Rd8 21.Nf4 Bf3+ 22.Kxf3) 16.a6 (16.f3 {-28.05 pws
Stockfish 14.1 64-bmi2} e4 17.d4 exf3+ 18.Nxf3 Qe4 19.Bg2 Bxg2 20.Ne1 Bh3 21.Kf2 Bxd4 22.exd4 Qxh4+ 23.Ke3 Qxd4+
24.Kf3) (16.Nf3 {-29.61 pws Stockfish 14.1 64-bmi2} Bxf3+ 17.Kxf3 Qd1+ 18.Kg3 Qxd2 19.a6 Rb8 20.axb7 Ne7 21.d4
Nf5+ 22.Kf3 exd4 23.exd4 Nxh4+ 24.Kg3 Nf5+ 25.Kg2 Nxd4) (16.f4 {-30.38 pws Stockfish 14.1 64-bmi2} exf4 17.a6 fxe3
18.Bxe3 Qc2+ 19.Bd2 Nd4+ 20.Ke1 Nb3 21.Bb4 Qc1+ 22.Ke2 bxa6 23.Kf2 Bd4+ 24.Kg3 Qxf1 25.h5 Bxg1) (16.d4 {-30.38 pws
Stockfish 14.1 64-bmi2} exd4 17.f4 d3+ 18.Kf2 Bf6 19.Nh3 Qd1 20.Kg1 Qxd2 21.Kxh1 Qxe3 22.Bg2 Nxa5) (16.Bh3 {-31.24
pws Stockfish 14.1 64-bmi2} Qxg1) (16.a6 {-32.15 pws Stockfish 14.1 64-bmi2} Rd8 17.Nf3 Qxd3+ 18.Ke1 Qb1+ 19.Ke2
Bxf3+ 20.Kxf3 Rxd2 21.Be2 Qh1+ 22.Kg3 Qg1+ 23.Kf3 e4+ 24.Kxe4 Qxf2 25.Bg4) (16.h5 {-40.61 pws Stockfish 14.1
64-bmi2} Rd8 17.d4 exd4 18.e4 Qxe4+ 19.Kd1 Qb1+ 20.Ke2 d3+ 21.Ke3 Bd4+ 22.Kf4 Qxf1 23.f3 Qxg1 24.Bc1 Qxc1+ 25.Kf5
d2) (16.Nh3 {-49.46 pws Stockfish 14.1 64-bmi2} Rd8 17.f4 Qxd3+ 18.Kf2 Qxd2+ 19.Kg1 Qxe3+ 20.Kxh1 exf4 21.Ng1 Rd1
22.h5 f3 23.a6 f2) (16.Be1 {-50.10 pws Stockfish 14.1 64-bmi2} Rd8 17.f4 Qc2+ 18.Bd2 Qxd3+ 19.Kf2 Qxd2+ 20.Ne2
exf4 21.Kg1 Qxe3+ 22.Kxh1 Rd1 23.Kg2 f3+ 24.Kg3 fxe2+ 25.Kh2 exf1=Q) (16.Bg2 {-91.73 pws Stockfish 14.1 64-bmi2}
Bxg2 17.Be1 O-O-O 18.f4 Qc2+ 19.Bd2 Qxd3+ 20.Kf2 Qxd2+ 21.Ne2 Rd3 22.e4 Bxe4 23.f5) bxa6 (16... Rd8 {-34.38 pws
Stockfish 14.1 64-bmi2} 17.f3 Qxd3+ 18.Kf2 Qxd2+ 19.Be2 Rd3 20.Kg3 Qxe3 21.Kh2 Qf2+ 22.Kxh1 Bd4 23.Nh3 Qe1+ 24.Bf1
Rxf3 25.Nf4 exf4 26.h5) (16... bxa6 {-30.15 pws Stockfish 14.1 64-bmi2} 17.f4 Rd8 18.Kf2 Qd1 19.Be1 exf4 20.Bh3
fxe3+ 21.Kf1 Rxd3) (16... O-O-O {-30.02 pws Stockfish 14.1 64-bmi2} 17.Bh3+ Kb8 18.Bf5 Bg2 19.Be1 Qc2+ 20.Bd2 Bc3
21.Nf3 Bxf3+ 22.Kxf3 Bxd2 23.d4 Qd1+ 24.Kg2) (16... Qc2 {-29.24 pws Stockfish 14.1 64-bmi2} 17.f4 Bc3 18.Nf3 Bxf3+
19.Kxf3 Qd1+ 20.Ke4 Bxd2 21.axb7 Rb8 22.fxe5 Qg4+ 23.Kd5 Nb4+ 24.Kc5) (16... e4 {-28.78 pws Stockfish 14.1
64-bmi2} 17.d4 Rd8 18.f3 exf3+ 19.Kf2 Qd1 20.Bc1 Qxc1 21.Nxf3 Qc2+ 22.Be2 Bxf3 23.Kxf3 Qf5+ 24.Kg3 Qe4 25.Kf2
Qxh4+ 26.Kg2) (16... h6 {-28.48 pws Stockfish 14.1 64-bmi2} 17.Nf3 Bxf3+ 18.Kxf3 Qd1+ 19.Kg3 Qxd2 20.axb7 Rb8
21.d4 Ke7 22.Bb5 Nb4 23.dxe5 Bxe5+ 24.Kg2 Qd1 25.Bc4) (16... Kf8 {-27.94 pws Stockfish 14.1 64-bmi2}) (16... f6
{-27.71 pws Stockfish 14.1 64-bmi2} 17.f3 bxa6 18.Nh3 Bxf3+ 19.Kxf3 Qd1+ 20.Be2 Qxd2 21.Nf2 Nb4 22.Ne4 Qe1 23.Nf2
f5 24.d4 exd4 25.exd4 Bxd4 26.Bb5+ Ke7) (16...  f5 {-27.63 pws Stockfish 14.1 64-bmi2} 17.Bh3 Qxg1 18.Be1 f4 19.h5
Rd8 20.h6 Qg6 21.Kf1 Qxh6 22.axb7 Qxh3+ 23.Ke2) 17.f3 (17.Be1 {-28.23 pws Stockfish 14.1 64-bmi2} Rd8 18.f4 Qc2+
19.Bd2 Qxd3+ 20.Kf2 Qxd2+ 21.Ne2 exf4) (17.Nf3 {-29.69 pws Stockfish 14.1 64-bmi2} e4 18.dxe4 Rd8 19.Nd4 Rxd4
20.f3 Bxf3+ 21.Kxf3 Ne5+ 22.Kg3 Rxd2 23.Bxa6) (17.f4 {-29.89 pws Stockfish 14.1 64-bmi2} Rd8 18.Kf2 Qd1 19.fxe5
Qxd2+ 20.Ne2 Rxd3 21.Kg1 Qxe3+ 22.Kxh1) (17.f3 {-30.99 pws Stockfish 14.1 64-bmi2} Qc2 18.f4 Bc3 19.Nf3 Bxf3+
20.Kxf3 Qxd2 21.Be2 exf4 22.Kxf4 Bd4 23.Ke4 Bxe3 24.Kd5) (17.d4 {-31.87 pws Stockfish 14.1 64-bmi2} exd4 18.f3 Qc2
19.f4 Bc3 20.Nf3 Bxf3+ 21.Kxf3 Qxd2 22.exd4 Nxd4+ 23.Ke4 f5+ 24.Kd5) (17.h5 {-33.61 pws Stockfish 14.1 64-bmi2}
Rd8 18.Nf3 Qxd3+ 19.Ke1 Qb1+ 20.Ke2 Bxf3+ 21.Kxf3 Rxd2 22.Bd3 Qh1+ 23.Kg3 Qg1+ 24.Kh3) (17.Bh3 {-34.77 pws
Stockfish 14.1 64-bmi2} Qxg1 18.Be1 Rd8 19.e4 Bf3+ 20.Ke3 Qxe1+ 21.Kxf3 Rxd3+ 22.Kg2 Qxe4+ 23.Kh2 Qxh4) (17.Nh3
{-79.50 pws Stockfish 14.1 64-bmi2} Rd8 18.f4 Qxd3+ 19.Kf2 Qxd2+ 20.Be2 exf4 21.Nxf4 Bc3 22.Kg3 Qxe3+ 23.Kh2 Qxf4+
24.Kh3) (17.Bg2 {M-8 Stockfish 14.1 64-bmi2} Bxg2 18.Be1 Qc2+ 19.Bd2 Bc3 20.Nf3 e4 21.dxe4 Rd8 22.Ke1 Bxd2+ 23.Ke2
Qd3+ 24.Kd1) (17.e4 {M-6 Stockfish 14.1 64-bmi2} Nd4+ 18.Ke3 Qxf1 19.Ba5 Qxg1 20.Bb4 Qc1+ 21.Bd2 Qf1 22.Ba5 Qe2#)
Nb4 (17... Nb4 {M-14 Stockfish 14.1 64-bmi2} 18.Kf2 Qc2 19.Be2 Qxd2 20.Kg3 Qxe3 21.Kh2 Qf2+ 22.Kxh1 Qxh4+ 23.Kg2
Nd5 24.Nh3 Ne3+ 25.Kh2 Bd4 26.Bd1 Nf5 27.Kg2 Qg3+ 28.Kf1 Qxh3+ 29.Ke1 Bc3+ 30.Kf2 Qh2+ 31.Kf1 Ne3#) (17... Qc2
{-31.67 pws Stockfish 14.1 64-bmi2} 18.f4 Bc3 19.Nf3 Bxf3+ 20.Kxf3 Qxd2 21.h5 exf4 22.Kxf4 Bd4 23.Kg3 Qxe3+ 24.Kg2
Qf2+ 25.Kh3 Qf3+ 26.Kh2 Qxh5+ 27.Kg2) (17... Rd8 {-31.53 pws Stockfish 14.1 64-bmi2} 18.Kf2 Qc2 19.Kg3 Qxd2 20.h5
Rxd3 21.Kh3 Qf2 22.h6 Qxf1+ 23.Kh4 Qe1+ 24.Kh5 Qxg1) (17... Qa2 {-30.92 pws Stockfish 14.1 64-bmi2} 18.Ke1 Qb1+
19.Kf2 Qc2 20.Kg3 Qxd2 21.Kh3 Qxe3 22.Kh2 Bxf3 23.Nh3 Bc3 24.d4 Bxd4) (17... f5 {-28.41 pws Stockfish 14.1
64-bmi2} 18.Nh3 Bxf3+ 19.Kxf3 Qd1+ 20.Be2 Qxd2 21.Nf2 Nb4 22.h5 Nc2 23.Nd1 O-O-O 24.Kg3 a5 25.e4 f4+ 26.Kh3)
(17... Qb2 {-28.40 pws Stockfish 14.1 64-bmi2} 18.Nh3 Bxf3+ 19.Kxf3 Qxd2 20.Be2 f5 21.Nf2 O-O 22.h5 f4 23.Kg2 fxe3
24.Ne4 Qc1 25.Ng3 a5 26.Bf3) (17... a5 {-28.25 pws Stockfish 14.1 64-bmi2} 18.Nh3 Bxf3+ 19.Kxf3 Qd1+ 20.Be2 Qxd2
21.Ng5 Ne7 22.Ne4 Qc1 23.Ng3 Nd5 24.e4 Qf4+ 25.Kg2 Ne3+ 26.Kh3 O-O-O) (17... Qb3 {-28.15 pws Stockfish 14.1
64-bmi2} 18.Nh3 Bxf3+ 19.Kxf3 Qd1+ 20.Be2 Qxd2 21.Nf2 Ne7 22.h5 Nd5 23.Nd1 a5 24.Kg4 Rd8 25.Bf3 Nxe3+ 26.Nxe3 Rd4+
27.Kg3 Qxe3) (17... g6 {-28.15 pws Stockfish 14.1 64-bmi2} 18.Nh3 Bxf3+ 19.Kxf3 Qd1+ 20.Be2 Qxd2 21.h5 gxh5 22.Nf2
f5 23.Kg2 Rg8+ 24.Kf1 Qxe3 25.Bxh5+ Ke7) (17... O-O {-28.07 pws Stockfish 14.1 64-bmi2} 18.Nh3 Bxf3+ 19.Kxf3 Qd1+
20.Be2 Qxd2 21.Ng5 Nb4 22.Ne4 Qc1 23.Ng3 Nd5 24.Nf5 g6 25.e4 Qh1+ 26.Kg3) (17... f6 {-28.01 pws Stockfish 14.1
64-bmi2} 18.Nh3) 18.Bxb4 (18.Kf2 {M-10 Stockfish 14.1 64-bmi2} Qc2 19.Ne2 Qxd2 20.Kg1 Bxf3 21.Kf2 Bxe2 22.Bxe2
Nxd3+ 23.Kf1 Qe1+ 24.Kg2 Qxe2+ 25.Kg3 Ne1 26.h5 Qg2+ 27.Kh4 Nf3#) (18.h5 {M-9 Stockfish 14.1 64-bmi2} Qxd3+ 19.Kf2
Qxd2+ 20.Ne2 Nd3+ 21.Kg3 Qe1+ 22.Kg4 Qxf1 23.Kh4 Nf2 24.Kg3 Qg2+ 25.Kh4 Qh3+ 26.Kg5 f6#) (18.Bxb4 {M-9 Stockfish
14.1 64-bmi2} Qxb4 19.Kf2 Qxh4+ 20.Ke2 Qh2+ 21.Kd1 Qxg1 22.Ke2 Qh2+ 23.Bg2 Qxg2+ 24.Kd1 Bc3 25.Kc1 Qb2+ 26.Kd1
Qd2#) (18.Nh3 {M-8 Stockfish 14.1 64-bmi2} Qxd3+ 19.Kf2 Qxd2+ 20.Kg3 Qe1+ 21.Nf2 Nd3 22.h5 Qxf2+ 23.Kh3 Bxf3 24.h6
g5 25.Bxd3 Qg2#) (18.d4 {M-8 Stockfish 14.1 64-bmi2} Qd3+ 19.Kf2 Qxd2+ 20.Ne2 Nd3+ 21.Kg3 Qe1+ 22.Kg4 Qxf1 23.Nf4
h5+ 24.Kf5 Qxf3 25.dxe5 Qg4#) (18.Bh3 {M-8 Stockfish 14.1 64-bmi2} Qxd3+ 19.Kf2 Qxd2+ 20.Ne2 Nd3+ 21.Kg3 Qxe2
22.h5 Bxf3 23.Bf1 Qxf1 24.Kh4 Qg2 25.e4 Qg4#) (18.f4 {M-8 Stockfish 14.1 64-bmi2} Qxd3+ 19.Kf2 Qxd2+ 20.Ne2 Nd3+
21.Kg3 Qe1+ 22.Kh3 Qxf1+ 23.Kg4 Qxe2+ 24.Kg5 Qg2+ 25.Kf5 Qg6#) (18.Be1 {M-7 Stockfish 14.1 64-bmi2} Nxd3 19.Bd2
Qc2 20.f4 Bc3 21.Nf3 e4 22.Bh3 exf3+ 23.Kf1 Qb1+ 24.Bc1 Qxc1#) (18.e4 {M-7 Stockfish 14.1 64-bmi2} Qxd3+ 19.Ke1
Nc2+ 20.Kf2 Bd4+ 21.Be3 Bxe3+ 22.Kg3 Bf4+ 23.Kg4 h5+ 24.Kf5 Ne3#) (18.Bg2 {M-7 Stockfish 14.1 64-bmi2} Bxg2
19.Bxb4 Qxg1 20.Be1 Qf1+ 21.Kd2 Bxf3 22.Kc2 Qxe1 23.Kb3 Qc3+ 24.Ka2 Qb2#) Qxb4 (18... Qxb4 {M-8 Stockfish 14.1
64-bmi2} 19.Bg2 Qb2+ 20.Ke1 Qxg2 21.Ne2 Qh2 22.Kd1 Bxf3 23.Kc2 Qxe2+ 24.Kb3 Qb2+ 25.Ka4 Bc6+ 26.Ka5 Qb5#)
(18... Qc2+ {-28.38 pws Stockfish 14.1 64-bmi2} 19.Bd2 Bc3 20.Kf2 Bxd2 21.Kg3 Bxe3 22.Ne2 Qd1 23.Bg2 Qxe2 24.Bxh1
Bf4+ 25.Kh3 Qxd3) (18... Rd8 {-26.61 pws Stockfish 14.1 64-bmi2} 19.Nh3 Qxb4 20.f4 Qb2+ 21.Ke1 Qc1+ 22.Kf2 Qd2+
23.Kg1 Qxe3+ 24.Kh2 Bd5 25.h5 exf4 26.Nxf4 Qxf4+ 27.Kh3 Qxf1+ 28.Kh4 Qxd3) (18... Qa2+ {-26.57 pws Stockfish 14.1
64-bmi2} 19.Ke1 Qb1+ 20.Kf2 Qxb4 21.f4 exf4 22.Nf3 Bxf3 23.Kxf3 fxe3 24.Kxe3 Qd4+ 25.Kd2 a5 26.Bg2 Qc3+ 27.Kd1
Qxd3+ 28.Kc1) (18... g6 {-25.81 pws Stockfish 14.1 64-bmi2} 19.Bd2 Qc2 20.f4 Bc3 21.Nf3 Bxf3+ 22.Kxf3 Qd1+ 23.Kf2
Qxd2+ 24.Be2 exf4 25.exf4 Qxf4+ 26.Kg2 Qd2 27.h5 Qg5+ 28.Kf1 gxh5 29.Kf2) (18... O-O-O {-25.37 pws Stockfish 14.1
64-bmi2}) (18... e4 {-25.17 pws Stockfish 14.1 64-bmi2} 19.fxe4 Qxb4 20.Kf2 Qd2+ 21.Be2 Bf6 22.Nf3 Bxf3 23.Kxf3
Bxh4 24.d4 Bg5 25.Bxa6 Qxe3+ 26.Kg2 Qxe4+ 27.Kg3 Qxd4) (18... h6 {-24.82 pws Stockfish 14.1 64-bmi2} 19.Kf2 Qxb4
20.Kg3 Qd2 21.Nh3 Bc3 22.Nf2 Qxe3 23.Nxh1 Be1+ 24.Kg2) (18... f6 {-24.82 pws Stockfish 14.1 64-bmi2} 19.Bd2 Qc2
20.d4 Bc3 21.Kf2 Qxd2+ 22.Ne2 Qe1+ 23.Kg1 Bxf3 24.dxe5 Bxe2) (18... g5 {-24.11 pws Stockfish 14.1 64-bmi2} 19.Bd2
Qc2 20.f4 gxh4 21.fxe5 Rb8 22.Bh3 Bc3 23.Bd7+ Kxd7 24.e6+ fxe6) 19.h5 (19.Kf2 {M-7 Stockfish 14.1 64-bmi2} Bc3
20.Kg3 Qb1 21.Kh2 Qxf1 22.Kxh1 Rb8 23.Kh2 Rb2+ 24.Ne2 Qxe2+ 25.Kh3 Qxf3#) (19.d4 {M-7 Stockfish 14.1 64-bmi2} exd4
20.Bh3 d3+ 21.Kf1 Qxh4 22.Bd7+ Kxd7 23.Ne2 d2 24.Ng3 d1=Q+ 25.Kf2 Qh2#) (19.Bg2 {M-6 Stockfish 14.1 64-bmi2} Rb8
20.Bxh1 Qb2+ 21.Ke1 Qh2 22.Ne2 Rb2 23.Bg2 Qxg2 24.Ng3 Rb1#) (19.Nh3 {M-6 Stockfish 14.1 64-bmi2} Bc3 20.Kf2 Qxh4+
21.Kg1 Bxf3 22.Nf4 exf4 23.Be2 Qg3+ 24.Kf1 Qe1#) (19.Bh3 {M-6 Stockfish 14.1 64-bmi2} Qb2+ 20.Ke1 Qb1+ 21.Ke2 Bc3
22.Bd7+ Kxd7 23.d4 Qc2+ 24.Kf1 Bg2#) (19.h5 {M-5 Stockfish 14.1 64-bmi2} Bc3 20.d4 Qb1 21.Bh3 Qc2+ 22.Kf1 Qd1+
23.Kf2 Qe1#) (19.f4 {M-4 Stockfish 14.1 64-bmi2} Bc3 20.d4 Qb2+ 21.Kd3 Bd5 22.Bg2 Qd2#) (19.Kd1 {M-4 Stockfish
14.1 64-bmi2} Qb1+ 20.Kd2 Rb8 21.Ne2 Rb2+ 22.Kc3 Qc2#) (19.e4 {M-4 Stockfish 14.1 64-bmi2} Bc3 20.d4 Qxd4 21.Bh3
Qd2+ 22.Kf1 Qe1#) Qh4 ?! (19... Bc3 {M-4 Stockfish 14.1 64-bmi2} 20.d4 Qb1 21.Bh3 Qc2+ 22.Kf1 Qd1+ 23.Kf2 Qe1#)
(19...  Qb1 {M-8 Stockfish 14.1 64-bmi2} 20.Kf2 Bc3 21.Ne2 Qe1+ 22.Kg1 Bxf3 23.h6 Bxe2 24.Kh2 Bf3 25.hxg7 Qh4+
26.Bh3 Qf2+ 27.Bg2 Qxg2#) (19... Rd8 {M-8 Stockfish 14.1 64-bmi2} 20.Bg2 Qb2+ 21.Ke1 Qxg2 22.Ne2 Qh2 23.Kd2 Bxf3
24.Kc2 Qxe2+ 25.Kb3 Rb8+ 26.Ka3 Qb2+ 27.Ka4 Qb4#) (19... Qb2+ {M-9 Stockfish 14.1 64-bmi2} 20.Ke1 Qb4+ 21.Kf2 Qh4+
22.Ke2 Qh2+ 23.Kd1 Qxg1 24.Ke2 Qh2+ 25.Bg2 Qxg2+ 26.Kd1 Bc3 27.Kc1 Qd2+ 28.Kb1 Qb2#) (19... Qh4 {M-11 Stockfish
14.1 64-bmi2} 20.Bh3 Qg3 21.d4 Qxg1 22.Bg4 exd4 23.exd4 Bc3 24.Bd7+ Kxd7 25.d5 Qe1+ 26.Kd3 Qd2+ 27.Ke4 Qd4+ 28.Kf5
Qxd5+ 29.Kf4) (19... h6 {-82.93 pws Stockfish 14.1 64-bmi2}) (19... f6 {-67.83 pws Stockfish 14.1 64-bmi2} 20.d4
exd4 21.Kf2 dxe3+ 22.Kg3 Be5+ 23.Kh3 Qf4 24.Ne2 Qxf3+ 25.Kh4) (19... g6 {-41.35 pws Stockfish 14.1 64-bmi2} 20.d4
Qb2+ 21.Ke1 exd4 22.Bd3 dxe3) (19... a5 {-37.56 pws Stockfish 14.1 64-bmi2} 20.f4 Qb2+ 21.Ke1 Qc1+ 22.Kf2 exf4
23.Bg2 fxe3+ 24.Kf3 Qxg1 25.Bxh1 Qf2+ 26.Kg4 e2 27.Bc6+ Ke7) (19... O-O-O {-28.23 pws Stockfish 14.1 64-bmi2}
20.f4 Qb2+ 21.Ke1 Qc1+ 22.Kf2 exf4 23.Bh3+ Kb8) 20.Nh3 (20.d4 {M-8 Stockfish 14.1 64-bmi2} Qh2+ 21.Kd3 Qxg1 22.Be2
Qb1+ 23.Kd2 Rb8 24.Bb5+ Rxb5 25.dxe5 Rb2+ 26.Kc3 Rh2+ 27.Kc4 Qb5#) (20.Bh3 {M-7 Stockfish 14.1 64-bmi2} Bc3 21.d4
e4 22.fxe4 Bxe4 23.Bd7+ Kxd7 24.Nf3 Qg4 25.Kf2 Qxf3+ 26.Kg1 Qg2#) (20.Bg2 {M-6 Stockfish 14.1 64-bmi2} Bxg2 21.d4
Rb8 22.Kd3 e4+ 23.fxe4 Qxe4+ 24.Kd2 Rb2+ 25.Ke1 Qb1#) (20.h6 {M-6 Stockfish 14.1 64-bmi2} Rb8 21.d4 e4 22.fxe4
Rb2+ 23.Kd1 Qf2 24.Bb5+ axb5 25.Kc1 Qxg1#) (20.Nh3 {M-6 Stockfish 14.1 64-bmi2} Rb8 21.d4 Rb2+ 22.Kd3 Bxf3 23.Ng5
Qf2 24.Be2 Qxe2+ 25.Kc3 Qc2#) (20.Kd2 {M-6 Stockfish 14.1 64-bmi2} Qb4+ 21.Ke2 Bc3 22.d4 Qb1 23.Bh3 Qc2+ 24.Kf1
Qd1+ 25.Kf2 Qe1#) (20.f4 {M-6 Stockfish 14.1 64-bmi2} Rb8 21.Nf3 Rb2+ 22.Nd2 Qh2+ 23.Bg2 Qxg2+ 24.Ke1 Qxd2+ 25.Kf1
Qd1#) (20.e4 {M-6 Stockfish 14.1 64-bmi2} Qh2+ 21.Kd1 Qxg1 22.d4 Qxf1+ 23.Kc2 Qc4+ 24.Kd2 Bxf3 25.dxe5 Qc3#)
(20.Kd1 {M-5 Stockfish 14.1 64-bmi2} Rb8 21.d4 Qf2 22.Bb5+ Rxb5 23.Ne2 Rb2 24.dxe5 Qf1#) e4 (20... Rb8 {M-5
Stockfish 14.1 64-bmi2} 21.d4 Rb2+ 22.Kd3 Bxf3 23.Ng5 Qf2 24.Be2 Qxe2+ 25.Kc3 Qc2#) (20... e4 {M-6 Stockfish 14.1
64-bmi2} 21.dxe4 Rb8 22.h6 Rb2+ 23.Kd3 Qe1 24.hxg7 Qxf1+ 25.Kc3 Qc1+ 26.Kd4 Rd2#) (20... Qxh5 {-83.04 pws
Stockfish 14.1 64-bmi2} 21.Kd2 Qxf3 22.Be2 Qxh3 23.Kc2 Qxe3 24.Bh5 Ke7 25.Bxf7 Kxf7 26.Kb1 Qxd3+ 27.Kxa1)
(20... Qg3 {-29.30 pws Stockfish 14.1 64-bmi2} 21.Kd1 Bxf3+ 22.Be2 Qxh3 23.Bxf3 Rb8 24.Bc6+ Ke7 25.d4 Rb2)
(20... f6 {-28.02 pws Stockfish 14.1 64-bmi2} 21.Nf2 Qxh5 22.Ng4 f5 23.e4 Bxf3+ 24.Kxf3 fxg4+ 25.Kg3 Qg5 26.Bg2
Qf4+ 27.Kh4 a5 28.Bh3) (20... h6 {-27.43 pws Stockfish 14.1 64-bmi2} 21.Nf2 Qxh5 22.Ng4 f5 23.Kf2 Qh4+ 24.Kg1 Bxf3
25.Nf6+ gxf6 26.Bg2 a5 27.Bxf3 Qg3+ 28.Kh1) (20... O-O {-27.30 pws Stockfish 14.1 64-bmi2} 21.Nf2 Qxh5 22.Ng4
Bxf3+ 23.Kxf3 f5 24.Bg2 fxg4+ 25.Ke2 Qh2 26.d4 exd4) (20... f5 {-26.78 pws Stockfish 14.1 64-bmi2}) (20... Kf8
{-26.38 pws Stockfish 14.1 64-bmi2} 21.h6 Qxh6 22.Nf2 Qh5 23.Ng4 f5 24.Bg2 fxg4 25.d4 exd4 26.exd4 gxf3+ 27.Ke3
Bxg2) (20... c5 {-26.23 pws Stockfish 14.1 64-bmi2} 21.h6 Qxh6 22.Kd2 Qh5 23.f4 Qf3 24.Be2 Qxh3 25.fxe5 Qh2 26.Ke1
Qxe2+ 27.Kxe2 Bxe5 28.e4 a5 29.Ke3 a4) (20... a5 {-26.15 pws Stockfish 14.1 64-bmi2} 21.d4 Qxh5 22.Kd2 Qxf3
23.Bb5+ Kf8 24.Ng1 Qf2+ 25.Be2 exd4 26.exd4) 21.h6 (21.dxe4 {M-6 Stockfish 14.1 64-bmi2} Rb8 22.h6 Rb2+ 23.Kd3 Qe1
24.hxg7 Qxf1+ 25.Kc3 Qc1+ 26.Kd4 Rd2#) (21.Nf4 {M-6 Stockfish 14.1 64-bmi2} Rb8 22.dxe4 Rb2+ 23.Kd3 Qe1 24.e5 Qb1+
25.Kc4 Rb5 26.Ne2 Qb3#) (21.Bg2 {M-6 Stockfish 14.1 64-bmi2} Rb8 22.dxe4 Rb2+ 23.Kd3 Qe1 24.e5 Qb1+ 25.Kd4 Rb5+
26.Kc4 Qb3#) (21.Kd2 {M-6 Stockfish 14.1 64-bmi2} Rb8 22.dxe4 Rb1 23.Bb5+ axb5 24.Kc2 Qe1 25.Nf2 Qc3+ 26.Kxb1
Qb2#) (21.Kd1 {M-6 Stockfish 14.1 64-bmi2} Rb8 22.dxe4 Rb1+ 23.Kc2 Qe1 24.Bb5+ axb5 25.Nf2 Qc3+ 26.Kxb1 Qb2#)
(21.d4 {M-5 Stockfish 14.1 64-bmi2} Rb8 22.Nf4 Rb2+ 23.Kd1 Qf2 24.Be2 Qg1+ 25.Bf1 Qxf1#) (21.fxe4 {M-5 Stockfish
14.1 64-bmi2} Rb8 22.Bg2 Rb2+ 23.Kd1 Qxh5+ 24.Kc1 Qe2 25.Bxh1 Qe1#) (21.f4 {M-4 Stockfish 14.1 64-bmi2} Bc3 22.Kd1
Qe1+ 23.Kc2 Rb8 24.dxe4 Qd2#) (21.h6 {M-4 Stockfish 14.1 64-bmi2} Bc3 22.dxe4 Rd8 23.Nf2 Rd2+ 24.Ke1 Qxf2#)
(21.Ng1 {M-4 Stockfish 14.1 64-bmi2} Bc3 22.Kd1 Qe1+ 23.Kc2 Rb8 24.fxe4 Rb2#) gxh6 (21... Bc3 {M-3 Stockfish 14.1
64-bmi2} 22.dxe4 Rd8 23.Nf2 Rd2+ 24.Ke1 Qxf2#) (21... exd3+ {M-4 Stockfish 14.1 64-bmi2} 22.Kxd3 O-O-O+ 23.Ke2 Bc3
24.Nf2 Rd2+ 25.Ke1 Qxf2#) (21... Rb8 {M-5 Stockfish 14.1 64-bmi2} 22.dxe4 Rb2+ 23.Kd3 Qe1 24.hxg7 Qxf1+ 25.Kc3
Qc1+ 26.Kd4 Rd2#) (21... Bxf3+ {M-5 Stockfish 14.1 64-bmi2} 22.Kd2 Rb8 23.dxe4 Rb2+ 24.Kc3 Qxe4 25.Bb5+ axb5
26.hxg7 Qxe3#) (21... exf3+ {M-5 Stockfish 14.1 64-bmi2} 22.Kd1 Qa4+ 23.Kc1 Qc6+ 24.Kd2 Qc3+ 25.Kd1 Rb8 26.hxg7
Rb1#) (21... gxh6 {M-6 Stockfish 14.1 64-bmi2} 22.dxe4 Rb8 23.Bg2 Rb1 24.e5 Bxg2 25.Nf4 Bf1+ 26.Kd2 Qe1+ 27.Kc2
Qc1#) (21... Qg3 {M-6 Stockfish 14.1 64-bmi2} 22.Nf4 Rb8 23.dxe4 Rb2+ 24.Kd3 Qe1 25.e5 Qb1+ 26.Kc4 Rb5 27.hxg7
Qc2#) (21...  Rd8 {M-6 Stockfish 14.1 64-bmi2} 22.Kd2 Rb8 23.hxg7 Rb2+ 24.Kc3 Qe1+ 25.Kc4 Rc2+ 26.Kb3 Qc3+ 27.Ka4
Ra2#) (21... Qf6 {M-7 Stockfish 14.1 64-bmi2} 22.Nf4 Rb8 23.d4 Rb2+ 24.Kd1 Bxf3+ 25.Ne2 Qh4 26.d5 Bxe2+ 27.Bxe2
Qh1+ 28.Bf1 Qxf1#) (21...  Qxh6 {M-7 Stockfish 14.1 64-bmi2} 22.dxe4 Rb8 23.Kf2 Qh4+ 24.Ke2 Rb2+ 25.Kd3 Qe1 26.e5
Qb1+ 27.Kd4 Rb5+ 28.Kc4 Qxf1#) 22.dxe4 (22.Kd1 {M-6 Stockfish 14.1 64-bmi2} Rb8 23.dxe4 Rb1+ 24.Kc2 Qe1 25.Bb5+
axb5 26.Nf2 Qxf2+ 27.Kxb1 Qb2#) (22.Kd2 {M-6 Stockfish 14.1 64-bmi2} Rb8 23.dxe4 Rb2+ 24.Kd3 Qe1 25.e5 Qb1+ 26.Kc4
Rb5 27.e4 Qxf1#) (22.Nf4 {M-6 Stockfish 14.1 64-bmi2} Rb8 23.dxe4 Rb2+ 24.Kd3 Qe1 25.e5 Qb1+ 26.Kd4 Rb5+ 27.Kc4
Qb3#) (22.dxe4 {M-6 Stockfish 14.1 64-bmi2} Rb8 23.Bg2 Rb1 24.e5 Bxg2 25.Nf4 Bf1+ 26.Kd2 Qe1+ 27.Kc2 Qc1#) (22.Bg2
{M-5 Stockfish 14.1 64-bmi2} exd3+ 23.Kd2 Qc4 24.e4 Bd4 25.Bxh1 Qc2+ 26.Ke1 Qc1#) (22.fxe4 {M-5 Stockfish 14.1
64-bmi2} Rb8 23.Bg2 Rb2+ 24.Kf1 Bxg2+ 25.Kg1 Qxh3 26.e5 Qh1#) (22.d4 {M-5 Stockfish 14.1 64-bmi2} Rb8 23.Kd2 Rb2+
24.Kc3 Qe1+ 25.Kc4 Rb5 26.Be2 Qxe2#) (22.Ng5 {M-4 Stockfish 14.1 64-bmi2} Bc3 23.Kd1 Qe1+ 24.Kc2 Rb8 25.fxe4 Qd2#)
(22.Ng1 {M-4 Stockfish 14.1 64-bmi2} Bc3 23.Kd1 Qe1+ 24.Kc2 Rb8 25.fxe4 Qd2#) (22.f4 {M-4 Stockfish 14.1 64-bmi2}
Bc3 23.Kd1 Qe1+ 24.Kc2 Rb8 25.d4 Rb2#) Rb8 (22... Rb8 {M-5 Stockfish 14.1 64-bmi2} 23.Bg2 Rb1 24.e5 Bxg2 25.Nf4
Bf1+ 26.Kd2 Qe1+ 27.Kc2 Qc1#) (22... Rd8 {M-5 Stockfish 14.1 64-bmi2} 23.Nf4 Qh2+ 24.Bg2 Bxg2 25.Nd5 Bh3+ 26.Kd1
Rg8 27.Kc1 Rg1#) (22... Qg3 {M-6 Stockfish 14.1 64-bmi2} 23.Nf4 Bxf3+ 24.Kd2 Rd8+ 25.Nd3 Qf2+ 26.Kc1 Qxf1+ 27.Ne1
Qxe1+ 28.Kc2 Qd1#) (22... O-O-O {M-6 Stockfish 14.1 64-bmi2} 23.Nf2 Bc3 24.Bh3+ Kb7 25.Nd3 Qxh3 26.Kd1 Qg2 27.Kc1
Rxd3 28.f4 Qb2#) (22... h5 {M-6 Stockfish 14.1 64-bmi2} 23.Nf4 Qh2+ 24.Bg2 O-O-O 25.Nd5 Qxg2+ 26.Ke1 Rxd5 27.exd5
Bc3+ 28.Kd1 Qd2#) (22... Rg8 {M-6 Stockfish 14.1 64-bmi2} 23.Nf4 Qh2+ 24.Kd3 Rd8+ 25.Nd5 Qb2 26.Bh3 Bxf3 27.Bd7+
Rxd7 28.Kc4 Qb5#) (22... Qh5 {M-6 Stockfish 14.1 64-bmi2} 23.Bg2 Bxg2 24.Nf4 Qh1 25.Nxg2 Qxg2+ 26.Kd3 O-O-O+
27.Kc4 Qb2 28.f4 Qc3#) (22... Bc3 {M-7 Stockfish 14.1 64-bmi2} 23.Nf4 Qe1+ 24.Kd3 Qd2+ 25.Kc4 Be5 26.Ne2 Qc2+
27.Kd5 Rd8+ 28.Kxe5 Qc5+ 29.Kf6 Qg5#) (22...  Be5 {M-7 Stockfish 14.1 64-bmi2} 23.Nf4 Qh2+ 24.Kd3 Rd8+ 25.Nd5 Bxf3
26.Bg2 Qxg2 27.Kc4 Qc2+ 28.Kb4 Bd6+ 29.Ka5 Qa2#) (22... a5 {M-7 Stockfish 14.1 64-bmi2} 23.Nf4 Qh2+ 24.Kd3 Qb2
25.Nd5 Bxf3 26.Nxc7+ Kd7 27.Bh3+ Kxc7 28.Kc4 Bxe4 29.Bd7 Qb4#) 23.Kd1 (23.Kd2 {M-5 Stockfish 14.1 64-bmi2} Rb2+
24.Kd3 Qe1 25.e5 Qb1+ 26.Kc4 Rb5 27.e4 Qxf1#) (23.f4 {M-5 Stockfish 14.1 64-bmi2} Rb2+ 24.Kd3 Qe1 25.Kc4 Qxf1+
26.Kd5 Rb5+ 27.Kc6 Qc1#) (23.Nf4 {M-5 Stockfish 14.1 64-bmi2} Rb2+ 24.Kd3 Qe1 25.e5 Qb1+ 26.Kd4 Rb5+ 27.Kc4 Qb3#)
(23.Nf2 {M-5 Stockfish 14.1 64-bmi2} Rb2+ 24.Kd3 Qxf2 25.Kc4 Qxf1+ 26.Kd5 Rb5+ 27.Kc6 Qc1#) (23.Bg2 {M-5 Stockfish
14.1 64-bmi2} Rb1 24.e5 Bxg2 25.Nf4 Bf1+ 26.Kd2 Qe1+ 27.Kc2 Qc1#) (23.Kd1 {M-5 Stockfish 14.1 64-bmi2} Rb1+ 24.Kc2
Qe1 25.Bb5+ axb5 26.Nf2 Qxf2+ 27.Kxb1 Qb2#) (23.Ng5 {M-4 Stockfish 14.1 64-bmi2} Rd8 24.Bg2 Bc3 25.f4 Rd2+ 26.Kf1
Qf2#) (23.Ng1 {M-4 Stockfish 14.1 64-bmi2} Rd8 24.Bg2 Bc3 25.f4 Rd2+ 26.Kf1 Bxg2#) (23.Kd3 {M-4 Stockfish 14.1
64-bmi2} Qe1 24.Kc2 Qc3+ 25.Kd1 Bxf3+ 26.Be2 Rb1#) (23.e5 {M-4 Stockfish 14.1 64-bmi2} Rb2+ 24.Kd3 Qa4 25.e4 Qb3+
26.Kd4 Rc2#) Rb2 ! (23... Rb1+ {M-4 Stockfish 14.1 64-bmi2} 24.Kc2 Qe1 25.Bb5+ axb5 26.Nf2 Qxf2+ 27.Kxb1 Qb2#)
(23... Bxf3+ {M-4 Stockfish 14.1 64-bmi2} 24.Be2 Qxh3 25.Kd2 Qg2 26.Kc1 Qxe2 27.e5 Qb2#) (23... Rb2 {M-4 Stockfish
14.1 64-bmi2} 24.Be2 Qxh3 25.Bb5+ axb5 26.Ke1 Qg3+ 27.Kf1 Qf2#) (23... Qd8+ {M-4 Stockfish 14.1 64-bmi2} 24.Kc2
Rb2+ 25.Kc3 Qd2+ 26.Kc4 Rb4+ 27.Kc5 Qd6#) (23... Bc3 {M-4 Stockfish 14.1 64-bmi2} 24.Kc2 Qe1 25.Bb5+ axb5 26.Nf2
Qd2+ 27.Kb3 Qb2#) (23...  O-O {M-4 Stockfish 14.1 64-bmi2} 24.Bb5 Rfd8+ 25.Kc2 Qe1 26.Kb3 Rxb5+ 27.Ka4 Qb4#)
(23... Rd8+ {M-5 Stockfish 14.1 64-bmi2} 24.Bd3 Bxf3+ 25.Kd2 Qxh3 26.Kc2 Rxd3 27.Kb1 Qg2 28.Kxa1 Rd1#) (23... a5
{M-5 Stockfish 14.1 64-bmi2} 24.Nf4 Qf2 25.Be2 Rb2 26.Bb5+ Rxb5 27.Ne2 Rb2 28.Nd4 Qd2#) (23... Rb3 {M-5 Stockfish
14.1 64-bmi2} 24.Bd3 Bxf3+ 25.Kd2 Rb2+ 26.Bc2 Qxe4 27.Kc3 Qxc2+ 28.Kd4 Rb5#) (23...  h5 {M-5 Stockfish 14.1
64-bmi2} 24.Bd3 Bxf3+ 25.Kd2 Qxh3 26.Bc2 Rd8+ 27.Ke1 Bc3+ 28.Kf2 Qg2#) 24.Bxa6 (24.Be2 {M-4 Stockfish 14.1
64-bmi2} Qxh3 25.Bb5+ axb5 26.Ke1 Qg3+ 27.Kf1 Qf2#) (24.Ng5 {M-3 Stockfish 14.1 64-bmi2} Qf2 25.Bb5+ axb5 26.Kc1
Qf1#) (24.Bxa6 {M-3 Stockfish 14.1 64-bmi2} Bxf3+ 25.Be2 Bxe2+ 26.Kc1 Qe1#) (24.Nf2 {M-3 Stockfish 14.1 64-bmi2}
Qxf2 25.Bb5+ axb5 26.Kc1 Qc2#) (24.f4 {M-3 Stockfish 14.1 64-bmi2} Bf3+ 25.Be2 Bxe2+ 26.Kc1 Qe1#) (24.e5 {M-3
Stockfish 14.1 64-bmi2} Bxf3+ 25.Be2 Bxe2+ 26.Kc1 Qe1#) (24.Ng1 {M-3 Stockfish 14.1 64-bmi2} Qd8+ 25.Bd3 Qxd3+
26.Ke1 Qb1#) (24.Nf4 {M-3 Stockfish 14.1 64-bmi2} Qf2 25.Be2 Qg1+ 26.Bf1 Qxf1#) (24.Bg2 {M-3 Stockfish 14.1
64-bmi2} Qd8+ 25.Ke1 Qd2+ 26.Kf1 Rb1#) (24.Bd3 {M-3 Stockfish 14.1 64-bmi2} Bxf3+ 25.Be2 Bxe2+ 26.Kc1 Qe1#) Rg8
(24... Bxf3+ {M-2 Stockfish 14.1 64-bmi2} 25.Be2 Bxe2+ 26.Kc1 Qe1#) (24... Qd8+ {M-2 Stockfish 14.1 64-bmi2}
25.Bd3 Qxd3+ 26.Ke1 Qb1#) (24...  O-O {M-3 Stockfish 14.1 64-bmi2} 25.Be2 Rd8+ 26.Bd3 Rxd3+ 27.Kc1 Qe1#) (24...
Ke7 {M-3 Stockfish 14.1 64-bmi2} 25.Be2 Rd8+ 26.Kc1 Qe1+ 27.Bd1 Qxd1#) (24...  Rb1+ {M-4 Stockfish 14.1 64-bmi2}
25.Kc2 Qe1 26.Bb5+ Ke7 27.Nf2 Qc3+ 28.Kxb1 Qb2#) (24... Qxh3 {M-4 Stockfish 14.1 64-bmi2} 25.Bb5+ Rxb5 26.Kd2 Bxf3
27.e5 Qg2+ 28.Kc1 Qb2#) (24... Kf8 {M-4 Stockfish 14.1 64-bmi2} 25.Be2 Qxh3 26.Bb5 Qxf3+ 27.Kc1 Qxe3+ 28.Kd1 Qd2#)
(24... Kd7 {M-4 Stockfish 14.1 64-bmi2} 25.Bb5+ Ke7 26.Nf2 Qxf2 27.Be2 Qxe2+ 28.Kc1 Qe1#) (24... Bg2 {M-4
Stockfish 14.1 64-bmi2} 25.Bb5+ Ke7 26.Nf2 Qxf2 27.Be2 Qxe2+ 28.Kc1 Qe1#) (24... c6 {M-4 Stockfish 14.1 64-bmi2}
25.Be2 Qd8+ 26.Ke1 Rb1+ 27.Bd1 Qxd1+ 28.Kf2 Qe1#) (24...  Rg8 {M-4 Stockfish 14.1 64-bmi2} 25.Bb5+ Ke7 26.Be2 Rd8+
27.Kc1 Qe1+ 28.Bd1 Qxd1#) 25.Ng1 (25.Bb5+ {M-4 Stockfish 14.1 64-bmi2} Ke7 26.Be2 Rd8+ 27.Kc1 Qe1+ 28.Bd1 Qxd1#)
(25.f4 {M-3 Stockfish 14.1 64-bmi2} Bf3+ 26.Be2 Bxe2+ 27.Kc1 Qe1#) (25.e5 {M-3 Stockfish 14.1 64-bmi2} Bxf3+
26.Be2 Bxe2+ 27.Kc1 Qe1#) (25.Be2 {M-3 Stockfish 14.1 64-bmi2} Qd8+ 26.Bd3 Qxd3+ 27.Ke1 Qb1#) (25.Bd3 {M-3
Stockfish 14.1 64-bmi2} Bxf3+ 26.Be2 Bxe2+ 27.Kc1 Qe1#) (25.Bf1 {M-3 Stockfish 14.1 64-bmi2} Bxf3+ 26.Be2 Bxe2+
27.Kc1 Qe1#) (25.Ng5 {M-3 Stockfish 14.1 64-bmi2} Qxg5 26.Bf1 Bxf3+ 27.Ke1 Qg3#) (25.Bc4 {M-3 Stockfish 14.1
64-bmi2} Bxf3+ 26.Be2 Bxe2+ 27.Kc1 Qe1#) (25.Ng1 {M-2 Stockfish 14.1 64-bmi2} Rxg1+ 26.Bf1 Rxf1#) (25.Nf2 {M-2
Stockfish 14.1 64-bmi2} Rg1+ 26.Bf1 Rxf1#) Rxg1+ (25... Rxg1+ {M-1 Stockfish 14.1 64-bmi2} 26.Bf1 Rxf1#)
(25... Qd8+ {M-2 Stockfish 14.1 64-bmi2} 26.Ke1 Rxg1+ 27.Bf1 Qd2#) (25... Ke7 {M-3 Stockfish 14.1 64-bmi2} 26.Nh3
Bxf3+ 27.Be2 Bxe2+ 28.Kc1 Qe1#) (25... Kf8 {M-3 Stockfish 14.1 64-bmi2} 26.Nh3 Bxf3+ 27.Be2 Bxe2+ 28.Kc1 Qe1#)
(25... Qxe4 {M-3 Stockfish 14.1 64-bmi2} 26.Bb5+ Ke7 27.fxe4 Rxg1+ 28.Bf1 Rxf1#) (25... Qf2 {M-3 Stockfish 14.1
64-bmi2} 26.Bb5+ Rxb5 27.Ne2 Rb2 28.e5 Qf1#) (25... Qh2 {M-3 Stockfish 14.1 64-bmi2} 26.Bb5+ Ke7 27.Ne2 Rg1+
28.Nxg1 Qd2#) (25... c6 {M-3 Stockfish 14.1 64-bmi2} 26.Nh3 Bxf3+ 27.Be2 Bxe2+ 28.Kc1 Qe1#) (25... Qe1+ {M-3
Stockfish 14.1 64-bmi2} 26.Kxe1 Rxg1+ 27.Bf1 Bg2 28.f4 Rxf1#) (25... Kd8 {M-3 Stockfish 14.1 64-bmi2} 26.Nh3 Bxf3+
27.Be2 Bxe2+ 28.Kc1 Qe1#) 26.Bf1 (26.Bf1 {M-1 Stockfish 14.1 64-bmi2} Rxf1#) Rxf1# (26... Rxf1# {Stockfish 14.1
64-bmi2}) (26... h5 {M-1 Stockfish 14.1 64-bmi2} 27.Kc1 Rxf1#) (26... Bxf3+ {M-1 Stockfish 14.1 64-bmi2} 27.Kc1
Rxf1#) (26... f5 {M-1 Stockfish 14.1 64-bmi2} 27.exf5 Rxf1#) (26... c6 {M-1 Stockfish 14.1 64-bmi2} 27.Kc1 Rxf1#)
(26... Ke7 {M-1 Stockfish 14.1 64-bmi2} 27.Kc1 Rxf1#) (26... Qd8+ {M-1 Stockfish 14.1 64-bmi2} 27.Ke1 Qd2#)
(26... Kd8 {M-1 Stockfish 14.1 64-bmi2} 27.Kc1 Rxf1#) (26... Kf8 {M-1 Stockfish 14.1 64-bmi2} 27.Kc1 Rxf1#)
(26... a5 {M-1 Stockfish 14.1 64-bmi2} 27.Kc1 Rxf1#)

** [TimeControl "-"][White "Acqua 2.0"][Black "gargle"]
[Event "Play against an engine"]
[Site "Lucas Chess R2.0"]
[Date "2022.09.19"]
[White "Acqua 2.0"]
[Black "gargle"]
[Result "0-1"]
[WhiteElo "?"]
[BlackElo "?"]
[Variant "Standard"]
[TimeControl "-"]
[ECO "C20"]
[Opening "English Opening: The Whale"]
[Termination "Unknown"]
[Annotator "lichess.org"]

1. c4 e5 2. e4 { C20 English Opening: The Whale } Bc5 3. d4 Bxd4 4. c5 Nc6 5. a4 Nf6 6. a5 d5 7. exd5 Nxd5 8. a6
   bxa6 9. g4 Be6 10. Bxa6 O-O 11. g5 Nf4 12. g6 Ng2+ 13. Ke2 Bg4+ 14. f3 Bh5 15. Nh3 Qh4 16. gxf7+ Rxf7 17. Ng5
   Rf5 18. Ne6 Ne3 19. Qa4 Bxf3+ 20. Kd3 Bxh1 21. Nxc7 Raf8 22. h3 Be4+ 23. Kd2 Nf1+ 24. Bxf1 Rxf1 25. Na3 R8f2# {
   Black wins. } 0-1
* [[https://www.chess.com/home][chess.com]]
** nelson
*** WAITING https://www.reddit.com/r/chessbeginners/comments/n9h2p8/my_guide_to_beating_the_chesscom_bot_nelson_1300/
*** TODO https://www.youtube.com/watch?v=Uk64fI-RqmE (2021) 
*** STARTED https://www.youtube.com/watch?v=U3sSGSRvSOc (2021) https://lichess.org/heXsY5Mr#90
1. e4 e5 2. Qh5 { C20 King's Pawn Game: Wayward Queen Attack } Nc6 3. Bc4 g6 4. Qf3 Nf6 5. d3 Bg7 6. Bg5
   O-O 7. Bxf6 Qxf6 8. Qxf6 Bxf6 9. a3 d6 10. Nd2 Be6 11. Ngf3 Rad8 12. Bxe6 fxe6 13. Rf1 d5 14. exd5 exd5 15. Rd1
   e4 16. dxe4 dxe4 17. Nxe4 Rfe8 18. Rxd8 Nxd8 19. b3 Rxe4+ 20. Kd2 Nc6 21. Re1 Rxe1 22. Kxe1 Kf7 23. c3
   Bxc3+ 24. Ke2 Nd4+ 25. Kd3 Nxf3 26. Kxc3 Nxh2 27. a4 Ng4 28. f3 Ne3 29. Kd3 Nxg2 30. b4 h5 31. Ke4 h4 32. b5
   h3 33. b6 axb6 34. f4 h2 35. a5 bxa5 36. f5 gxf5+ 37. Kxf5 h1=Q 38. Ke4 Qd1 39. Ke5 c5 40. Ke4 c4 41. Ke5
   c3 42. Ke4 c2 43. Ke5 c1=Q 44. Ke4 Qe3+ 45. Kf5 Qdf3# { Black wins by checkmate. } 0-1
*** STARTED https://www.youtube.com/watch?v=KH2LXUoVGkU (2021) https://lichess.org/jXDTuE75#74
1. e4 c5 2. Qh5 d6 3. Bc4 e6 4. f4 Nf6 5. Qf3 Be7 6. e5 Nfd7 7. Be2 O-O 8. b3 dxe5 9. Bb5 exf4 10. g3
   fxg3 11. Bxd7 Bxd7 12. hxg3 Bc6 13. Qd3 Bxh1 14. Qxd8 Rxd8 15. Bb2 Bf6 16. Bxf6 gxf6 17. c4 Nc6 18. Nc3
   Rd3 19. Na4 b6 20. Kd1 Rad8 21. Ne2 Rxd2+ 22. Ke1 Bf3 23. Ng1 Rd1+ 24. Rxd1 Bxd1 25. Nh3 Bg4 26. Nf2
   f5 27. Nxg4 fxg4 28. Nb2 h5 29. a4 Nd4 30. Kf1 Nxb3 31. Kg1 Rd2 32. Kf1 Rxb2 33. a5 bxa5 34. Ke1 a4 35. Kd1
   a3 36. Ke1 a2 37. Kd1 a1=Q#
*** STARTED https://www.youtube.com/watch?v=8o9oYjF0Bag (2021) https://lichess.org/1zWavLhb#144
1. e4 g6 { B06 Modern Defense } 2. Qg4 Bg7 3. Qh4 e5 4. Qxd8+ Kxd8 5. d4 d6 6. dxe5 Bxe5 7. Bg5+ f6 8. Bc1
   Be6 9. Nf3 Nc6 10. Be2 Kd7 11. Bb5 a6 12. Nxe5+ fxe5 13. Bxc6+ bxc6 14. a4 Nf6 15. f3 Rab8 16. b3 d5 17. Bg5
   Nh5 18. exd5 cxd5 19. O-O Nf4 20. Re1 Kd6 21. Bf6 Rhe8 22. Bxe5+ Kc5 23. Bxf4 Bf5 24. Rxe8 Rxe8 25. Na3
   Kb4 26. g4 Bc8 27. Bd2+ Kc5 28. Re1 Rd8 29. Be3+ d4 30. Bg5 Rd5 31. Be7+ Kc6 32. Re4 d3 33. cxd3 Rxd3 34. Kg2
   Rxb3 35. Rc4+ Kb7 36. Rb4+ Rxb4 37. Bxb4 Bd7 38. Bd2 Bxa4 39. Nc4 Kc6 40. Bb4 Kb5 41. Nb2 Kxb4 42. Nd3+
   Kc4 43. Nb2+ Kb3 44. Nd1 c5 45. Kh3 Kc4 46. Nb2+ Kb3 47. Nd3 c4 48. Nc5+ Kb4 49. Nxa6+ Kb5 50. Nc7+ Kc6 51. Ne6
   c3 52. Nd8+ Kd6 53. Nf7+ Ke6 54. Ng5+ Ke7 55. Kg3 c2 56. Kh4 c1=Q 57. Nxh7 Qh6+ 58. Kg3 Qxh7 59. g5 Qh5 60. Kg2
   Qxg5+ 61. Kf2 Qd2+ 62. Kg3 Bd7 63. h3 Kf6 64. h4 g5 65. h5 Qf4+ 66. Kg2 Qh4 67. Kf1 Bh3+ 68. Ke2 Qxh5 69. Kd3
   Qxf3+ 70. Kd2 Bf5 71. Kc1 Qc3+ 72. Kd1 Bg4# { Black wins by checkmate. } 0-1
*** WAITING https://www.youtube.com/watch?v=AHe8heB3kjg (2021)
*** STARTED [[https://www.youtube.com/watch?v=cY9zitJFglc?t=193][Stopping Early Queen Attacks]]
*** STARTED [[https://www.chess.com/a/2SG3VCcgW2ovv][example on how to beat Nelson]]
*** https://www.chess.com/analysis/game/computer/14435221?tab=review
1. e4 Nf6 2. Qf3 e5 3. Qh3 d5 4. Qb3 Nc6 5. exd5 Nxd5 6. Qf3 Nd4 7. Qe4 Bf5 8. Qxe5+ Qe7 9. Qxe7+ Bxe7 10. c4
   Nf4 11. g3 Nd3+ 12. Bxd3 Bxd3 13. Na3 Bc2 14.  Nxc2 Nxc2+ 15. Kd1 Nxa1 16. d4 Rd8 17. Nf3 Bb4 18. a3 Ba5 19. b4
   Bb6 20. c5 Bxc5 21. bxc5 b6 22. Re1+ Kf8 23. Bg5 Rd5 24. c6 f6 25. Bh4 Kf7 26. Re3 Re8 27. Rxe8 Kxe8 28. g4
   Nb3 29. Bg3 Nxd4 30. Nxd4 Rxd4+ 31. Kc1 Rxg4 32. f3 Ra4 33. Kb2 Rc4 34. Be1 Rxc6 35. Bf2 Re6 36. Kc1 f5 37. f4
   Re4 38. Bg3 Ra4 39. Kd2 Rxa3 40. Ke2 Ra2+ 41. Kf3 b5 42. Bf2 b4 43. Bd4 b3 44. h3 Rh2 45. Bxg7 Rxh3+ 46. Kg2
   Rd3 47.  Be5 Rd2+ 48. Kf3 b2 49. Bxb2 Rxb2 50. Ke3 a5 51. Kd3 a4 52. Kc3 Rh2 53. Kb4 h5 54. Ka3 Rh3+ 55. Kxa4
   Rf3 56. Kb4 Rxf4+ 57. Kb5 h4 58. Ka5 h3 59. Kb5 h2 60. Kc6 h1=Q+ 61. Kxc7 Rd4 62. Kb6 Qc1 63. Kb7 Rb4+ 64. Ka7
   Qa1# 0-1
*** https://www.chess.com/analysis/game/computer/18466173?tab=analysis
1. e4 e5 2. Qh5 Nc6 3. c3 g6 4. Qd1 d6 5. d4 Nf6 6. Qd3 Bd7 7. d5 Nd4 8. cxd4 exd4 9. Qxd4 Qe7 10. f3 c5 11. dxc6
   Bxc6 12. Nh3 Bg7 13. Qd2 O-O 14. b4 Nxe4 15. fxe4 Qxe4+ 16. Be2 Bxa1 17. Na3 a6 18. Nf4 Be5 19. Nc4
   Bxf4 20. Qxf4 Qxf4 21. Bxf4 Bxg2 22. Rg1 Bd5 23. Bxd6 Rfd8 24. Bc7 Rdc8 25. Be5 Bxc4 26. Bf3 Bxa2 27. Bxb7
   Rab8 28. Bxc8 Rxc8 29. Rg2 Re8 30. Rxa2 Rxe5+ 31. Kf2 Re4 32. Ra5 Rxb4 33. Rxa6 Rb2+ 34. Kg3 h5 35. Rf6
   Rb4 36. Kf3 h4 37. Rc6 Rb3+ 38. Ke2 h3 39. Kd1 Rb2 40. Rc2 Rb1+ 41. Ke2 Rh1 42. Kd3 Rg1 43. Kc3 Rg2 44. Rc1
   Rxh2 45. Kb3 Rg2 46. Kc4 h2 47. Kd5 Rg1 48. Rc8+ Kg7 49. Rc7 h1=Q+ 50. Kc5 Qh2 51. Re7 Rg2 52. Kc6 Re2 53. Rxe2
   Qxe2 54. Kb7 f5 55. Kc7 g5 56. Kd7 g4 57. Kd6 f4 58. Kd5 g3 59. Kd6 f3 60. Kc6 f2 61. Kd7 g2 62. Kc7
   g1=Q 63. Kc8 f1=Q 64. Kc7 Qe6 65. Kb7 Qff7+ 66. Kb8 Qga7# 0-1
* [[https://lichess.org/][lichess.org]]
** game
*** numbers (a+b)
    a (in minutes) is the time you have for thinking and playing your moves in the whole game
    b (in seconds) is the number of time that is added everytime you play a move
    total time for game = a+b*(number of moves)
*** types
    https://en.wikipedia.org/wiki/Fast_chess
    https://lichess.org/faq#time-controls
    bullet      one or two minutes per side
    blitz       less than 10 minutes per side (often 5 minutes)
    rapid       10-60 minutes per side (often 30 minutes)
    classical   may allow two hours per player for the first forty moves, then an additional hour per player
** stockfish
*** level 3
**** https://lichess.org/DnP2OtMm/black
1. e4 e5 2. Nf3 Nf6 3. Nxe5 { C42 Russian Game } Bd6 4. Nc4 Bf4 5. d3 Nc6 6. Nc3 d5 7. Bd2 dxc4 8. d4
   Bxd2+ 9. Kxd2 O-O 10. d5 Nd4 11. f3 Bd7 12. e5 Nxd5 13. h4 Nf4 14. Bxc4 Be6 15. g3 Bxc4 16. gxf4 Nxc2+ 17. Kxc2
   Qxd1+ 18. Nxd1 Rad8 19. Ne3 Bd3+ 20. Kc1 Be2 21. Kc2 Bxf3 22. Rhe1 Be4+ 23. Kb3 Rfe8 24. a4 Bc6 25. Kc3
   b5 26. a5 a6 27. Red1 Bf3 28. Rf1 Be2 29. Rad1 Bxf1 30. Rxf1 f6 31. b3 fxe5 32. Nc2 exf4 33. Rf2 Rf8 34. Nb4
   f3 35. Nxa6 c5 36. Nxc5 Rf4 37. a6 Ra8 38. Rf1 b4+ 39. Kb2 f2 40. Ne6 Rxh4 41. Nc7 Rf8 42. Nd5 Rh6 43. Nxb4
   Rh4 44. Nd3 Rd4 45. Nc5 Rd2+ 46. Kc3 Rfd8 47. Rh1 Rd1 48. Rxd1 Rxd1 49. a7 Ra1 50. a8=R+ Rxa8 51. Kc4
   f1=Q+ 52. Nd3 Qb1 53. Nc5 Rc8 54. b4 h5 55. Kd5 Qxb4 56. Ne4 Rc5+ 57. Nxc5 Qf4 58. Ne6 Qf1 59. Nd4 h4 60. Ke5
   h3 61. Ke6 h2 62. Ke5 h1=Q 63. Nf5 Qe1+ 64. Kf4 g6 65. Ne3 Qh3 66. Ke4 Qexe3+ 67. Kd5 Qd7+ 68. Kc4 Qc1+ 69. Kb3
   Qb7+ 70. Ka4 Qa1# { Black wins by checkmate. } 0-1

* [[https://listudy.org/en][listudy.org]]
* podcasts
** [[https://open.spotify.com/show/74A0JotybXUvnviTCzsSUp][How To Chess]]
** [[https://www.perpetualchesspod.com/][The Perpetual Chess Podcast]]
* study
** [[https://www.youtube.com/watch?v=Ao9iOeK_jvU][Chess Fundamentals, John Bartholomew]]
*** TODO [[https://www.youtube.com/watch?v=Ao9iOeK_jvU][Chess Fundamentals #1: Undefended Pieces]]
*** TODO [[https://www.youtube.com/watch?v=TWJ6751RRis][Chess Fundamentals #2: Coordination]]
*** TODO [[https://www.youtube.com/watch?v=I5o2d9slUCM][Chess Fundamentals #3: Typical Mistakes]]
*** TODO [[https://www.youtube.com/watch?v=h-JGqEiNs-I][Chess Fundamentals #4: Pawn Play]]
*** TODO [[https://www.youtube.com/watch?v=8kdjSqNcViw][Chess Fundamentals #5: Trades]]
** [[https://www.youtube.com/watch?v=U2huVf1l4UE][Climbing the Rating Ladder, John Bartholomew]]
** [[https://www.youtube.com/playlist?list=PLUjxDD7HNNThftJtE0OIRFRMMFf6AV_69][Building Chess Habits, chessbrah]]
** https://www.wikihow.com/Category:Chess
** https://www.wikihow.com/Win-Chess-Openings:-Playing-Black?amp=1
** https://www.wikihow.com/Become-a-Better-Chess-Player?amp=1
** https://professorchess.com/
** https://goldenchess.in/2021/01/13/13-smart-chess-training-ideas-that-work/
** https://www.youtube.com/results?search_query=chessbrah+building+habbits
** https://www.reddit.com/r/chess/comments/sbsdht/calculation_advice_seeing_opponents_moves/
** https://learn.chessbase.com/en/page/the-value-of-the-pieces-in-chess

   | piece  | value |
   |--------+-------|
   | Queen  |   9   |
   | Rook   |   5   |
   | Bishop |   3   |
   | Knight |   3   |
   | Pawn   |   1   |

   Two bishops coordinate very well as the bishop pair because they can operate on all the squares on the board In
   an open position (one with few blocked pawns) the bishop pair is stronger thana bishop and a knight.  So the
   bishop is worth a tad more than the knight.  In a closed position in which the bishops are restricted by blocked
   pawn chains the knight, on the other hand, is more mobile.

** https://chessdelta.com/11-best-chess-opening-principles-for-starters-step-by-step/
    1. Move Center Pawns to Center Squares.
    2. Dont make unnecessary pawn moves.
    3. Move the Kingside Pieces first.
    4. Then move Queenside Pieces.
    5. Dont bring out the major pieces early!
    6. Develop knights before bishops.
    7. Dont repeat the moves!
    8. Castle within the first 5-10 moves.
    9. Attach your Rooks.
   10. Protect your castled position.
   11. When attacked-Use your Mind.

** pawn chains
   attack a pawn chain at its base!
   black d5, e6, f7 is a pawn chain, d5 is its base
   white d4, e5 is a pawn chain, d4 is its base; b2, c3, d4, e5 is a strong white pawn chain
** http://www.openchessbooks.org/
** [[https://www.chess.com/article/view/learning-chess-patterns-is-easy][Learning Chess Patterns Is Easy, Silman]]
** notes from https://news.ycombinator.com/item?id=32045763
*** I would also recommend Daniel Naroditsky's speed run video series:

[[https://www.youtube.com/watch?v=Ytkf3qZTj74][Grandmaster Naroditsky Chess Speedrun Pt. 1]]

Naroditsky has the most accessible teaching videos on YouTube as far as Im concerned.  Hes also writing a
regular chess column for NYT.

*** If youre intimidated by playing other humans, you can try the Maia 1 bot on Lichess.

Itll likely beat you up for a while if youre a beginner, but its a bot designed to play more like a human, and
itll help you get the reps to feel more comfortable playing other humans

*** Chess Brah Building Habits series on YouTube.

For those of you thinking about picking up chess, Id highly recommend watching the Chess Brah Building Habits
series on YouTube.  Watch the first five or so videos, and just start practicing those habits in rapid games
(recommend 15 minute with 10 second increment on lichess, which shows up as 15+10).  Embrace the losses, and just
keep working on not hanging your pieces for free.

** [[https://lichess.org/study/DAmLK0ug][Queen's Gambit]]
   1.  d4 d5
   2.  c4
***    ...  dxc4 (Queens Gambit Accepted)
   3.  Nf3       (to prevent ... e5)
       ...  Nf6
   4.  e3        (so that our Bishop f1 can take back c4)
****   ...  b5   (to greedy, should have played e6)
   5.  a4        (because it is covered by our Queen)
       ...  c6
   6.  axb5 cxb5
   7.  b3        (black behind in development, white has center, destroys black's queenside, may attack the King)
****   ...  e6
   5.  Bc4  c5   (black will try to take on d4 at some point)
   6.  O-O  a6   (black wants to go ... b5 and ... Bb7)
   7.  a4        (attack b5, coverted by our Queen)
       ...  Nc6
   8.  Qe2  cxd4
   9.  Rd1       (pawn d4 pinned to the black Queen)
       ...  Be7
   10. exd4 O-O
   11. Nc3
***    ...  e6   (Queens Gambit declined)
   3.  Nc3  Nf6
   4.  cxd5 exd5
   5.  Bg5       (pin black's Kf6 against black Queen)
       ...  Be7
   6.  e3        (to bring our Bf1 in the game)
       ...  c6   (Carlsbad Pawn Structure)
   7.  Bd3  Nbd7
   8.  Qc2       (put pressure on h7)
       ...  O-O
   9.  O-O       (King side caste is better, but it's not explained)
      *** TO BE CONTINUED ***
***    ...  c6   (Slav and Semi-Slav Defenses)
** TODO https://nextlevelchess.blog/5-costly-amateur-mistakes/
** books
*** https://z-lib.org/
*** http://www.pdfdrive.com/chess-books.html
* The Complete Chess Course - Fred Reinfeld
** Book Two, The Nine Bad Moves, pag. 38
*** Neglecting Development of Your Pieces, pag. 38
**** Disastrous Pawn Moves, pag. 38, https://lichess.org/rGLXTaIs
1. e4 e5 2. Nf3 Nc6 3. Bc4 f6 4. Nh4 g5 5. Qh5+ Ke7 6. Nf5#
**** Poor Development, Poor Defense, pag. 39, https://lichess.org/DOcRrI9f
1. e4 e5 2. Nf3 Nc6 3. Bb5 Nf6 4. O-O Nxe4 5. d4 Nd6 6. Bxc6 bxc6 7. dxe5 Nb7 8. Nd4 Be7 9. Nf5 Bf8 10. Re1
   g6 11. Nd6+ Bxd6 12. exd6+ Kf8 13. Bh6+ Kg8 14. Qd4 f6 15. Qc4#
**** White Neglects his Kings Welfare, pag. 39, https://lichess.org/ta5REAVy
1. e4 e5 2. Nc3 Nc6 3. f4 Bc5 4. Nf3 d6 5. f5 Nf6 6. h3 d5 7. Nxe5 Nxe4 8. Nf3 Qh4+ 9. Nxh4 Bf2+ 10. Ke2
   Nd4+ 11. Kd3 Nc5#
**** How to Lose in Nine Moves, pag. 40, https://lichess.org/54x6JjnK
1. f4 Nf6 2. c4 d5 3. cxd5 Nxd5 4. d3 e5 5. fxe5 Bb4+ 6. Bd2 Ne3 7. Qa4+?? b5 8. Qxb5+ Bd7 9. Qb7 Bc6
**** Thoughtless Development Proves Disastrous, pag. 41, https://lichess.org/Qa0beRvP
1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 b5 5. Bb3 Na5? 6. O-O Nxb3 7. axb3 d6 8. d4 Bg4 9. dxe5 Bxf3 10. Qxf3
   dxe5 11. Rd1 Qf6 12. Qd3 Qc6 13. Rxa6!!
**** Good Development Trounces Poor Development, pag. 42, https://lichess.org/wKUZPa6X
1. e4 e5 2. Nf3 Nc6 3. d4 exd4 4. Bc4 Bc5 5. O-O d6 6. c3 Bg4 7. Qb3 Bxf3 8. Bxf7+ Kf8 9. Bxg8 Rxg8 10. gxf3
   g5! 11. Qe6 Ne5! 12. Qf5+ Kg7! 13. Kh1 Kh8 14. Rg1 g4! 15. f4 Nf3 16. Rxg4 Qh4!! 17. Rg2 Qxh2+! 18. Rxh2 Rg1#!
**** How Exchanges May Influence Development, pag. 43, https://lichess.org/gF1uCujo
1. e4 e5 2. f4 exf4 3. Nf3 g5 4. h4 g4 5. Ne5 Nf6 6. Nxg4 Nxe4 7. Qe2 d5 8. d3 Bxg4 9. Qxg4 Ng3 10. Rh3
   Bd6 11. Bxf4 Qe7+ 12. Kf2 Bxf4 13. Qxf4 Nxf1 14. Nc3 O-O 15. Kxf1 c6 16. Re1 Qd8 17. Rg3+ Kh8 18 Qh6
   Rg8 19. Re8!! Qxe8 20. Qf6+ Rg7 21. Qxg7#
*** Exposing your King to Attack, pag. 44
**** https://lichess.org/editor/r1bqk2r/pppn1pp1/5n1p/2B5/2B1p3/2N5/PPP1Q1PP/R4RK1_w_-_-_0_1
**** https://lichess.org/editor/2r1r1k1/p4ppp/bnBq4/3P3n/3P3P/1P3P2/P1PKN3/R1BQR3_b_-_-_0_1
1... Rxc6 2. dxc6 Bxe2 3. Rxe2 Qxd4+ 4. Ke1 Qg1+ 5. Kd2 Rd8+ 6. Kc3 Qc5+ 7. Kb2 Na4+! White resigns
**** Black Provokes a Knight-Hunt, pag. 45, https://lichess.org/CkikHpfr
1. e4 e5 2. Nf3 Nc6 3. Bc4 Bc5 4. b4 Bxb4 5. c3 Ba5 6. d4 exd4 7. O-O Nf6 8. Ba3 Bb6 9. Qb3 d5 10. exd5
   Na5 11. Re1+ Be6 12. dxe6 Nxb3 13. exf7+ Kd7 14. Be6+ Kc6 15. Ne5+ Kb5 16. Bc4+ Ka5 17. Bb4+ Ka4 18. axb3#
**** White Neglects Castling 1, pag. 45, https://lichess.org/0DxJpOfz
1. e4 e5 2. Nf3 Nc6 3. Bc4 Bc5 4. c3 Bb6 5. d4 Qe7 6. d5 Nd8 7. Be2 d6 8. h3 f5 9. Bg5 Nf6 10. Nbd2 O-O 11. Nh4
   fxe4 12. Nxe4 Nxe4 13. Bxe7 Bxf2+ 14. Kf1 Ng3#
**** White Neglects Castling 2, pag. 45, https://lichess.org/9vDvNeIV
1. Nc7+ Bxc7 2. Rxc7 Qxc7 3. Qxa8+ Ke7 4. Qxh8
